// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/colortokens/terraform-provider-xshield/internal/sdk/models/shared"
	"net/http"
)

type ListFieldsRequest struct {
	// scope
	Scope *string `queryParam:"style=form,explode=true,name=scope"`
}

func (o *ListFieldsRequest) GetScope() *string {
	if o == nil {
		return nil
	}
	return o.Scope
}

type ListFieldsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	MetadataResponse *shared.MetadataResponse
	// Bad Request
	ErrorResponse *shared.ErrorResponse
}

func (o *ListFieldsResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *ListFieldsResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *ListFieldsResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *ListFieldsResponse) GetMetadataResponse() *shared.MetadataResponse {
	if o == nil {
		return nil
	}
	return o.MetadataResponse
}

func (o *ListFieldsResponse) GetErrorResponse() *shared.ErrorResponse {
	if o == nil {
		return nil
	}
	return o.ErrorResponse
}
