// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/colortokens/terraform-provider-xshield/internal/sdk/models/shared"
	"net/http"
)

type TagBasedPolicyBulkTemplateUnApplyRequest struct {
	// Tag Based Policy ID
	TagbasedpolicyID string `pathParam:"style=simple,explode=false,name=tagbasedpolicyId"`
	// Template list to remove
	RequestBody shared.TemplateList `request:"mediaType=application/json"`
}

func (o *TagBasedPolicyBulkTemplateUnApplyRequest) GetTagbasedpolicyID() string {
	if o == nil {
		return ""
	}
	return o.TagbasedpolicyID
}

type TagBasedPolicyBulkTemplateUnApplyResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *TagBasedPolicyBulkTemplateUnApplyResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *TagBasedPolicyBulkTemplateUnApplyResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *TagBasedPolicyBulkTemplateUnApplyResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
