// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type AutoDeploymentMode string

const (
	AutoDeploymentModeTest    AutoDeploymentMode = "test"
	AutoDeploymentModeEnforce AutoDeploymentMode = "enforce"
	AutoDeploymentModeDisable AutoDeploymentMode = "disable"
)
