// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// NamedNetworkList - List of named network IDs
type NamedNetworkList struct {
	// Optional comment
	Comment *string `json:"comment,omitempty"`
	// List of named network IDs
	Namednetworks []string `json:"namednetworks"`
}
