// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type TagBasedPolicyResponse struct {
	ID                                     *string                         `json:"tagBasedPolicyId,omitempty"`
	Description                            *string                         `json:"description,omitempty"`
	TagBasedPolicyName                     *string                         `json:"tagBasedPolicyName,omitempty"`
	TargetBreachImpactScore                *int64                          `json:"targetBreachImpactScore,omitempty"`
	Timeline                               *int64                          `json:"timeline,omitempty"`
	Criteria                               *string                         `json:"criteria,omitempty"`
	CriteriaAsParams                       *string                         `json:"criteriaAsParams,omitempty"`
	Namednetworks                          []MetadataNamedNetworkReference `json:"namednetworks,omitempty"`
	Templates                              []TemplateReference             `json:"templates,omitempty"`
	Milestones                             []TagBasedPolicyMilestone       `json:"milestones,omitempty"`
	MatchingAssets                         *int64                          `json:"matchingAssets,omitempty"`
	BaselineBreachImpactScore              *int64                          `json:"baselineBreachImpactScore,omitempty"`
	BaselineMatchingAssets                 *int64                          `json:"baselineMatchingAssets,omitempty"`
	CreatedAt                              *SafeTime                       `json:"createdAt,omitempty"`
	PolicyAutomationConfigurable           *bool                           `json:"policyAutomationConfigurable,omitempty"`
	LowestInboundSegmentAssetPolicyStatus  *string                         `json:"lowestInboundSegmentAssetPolicyStatus,omitempty"`
	LowestOutboundSegmentAssetPolicyStatus *string                         `json:"lowestOutboundSegmentAssetPolicyStatus,omitempty"`
	InboundAutoSyncDeploymentMode          *string                         `json:"inboundAutoSyncDeploymentMode,omitempty"`
	InboundAutoSyncIntervalMinutes         *int64                          `json:"inboundAutoSyncIntervalMinutes,omitempty"`
	InboundAutoSyncIncludeViolations       *bool                           `json:"inboundAutoSyncIncludeViolations,omitempty"`
	InboundAutoSyncViolationThreshold      *int64                          `json:"inboundAutoSyncViolationThreshold,omitempty"`
	OutboundAutoSyncDeploymentMode         *string                         `json:"outboundAutoSyncDeploymentMode,omitempty"`
	OutboundAutoSyncIntervalMinutes        *int64                          `json:"outboundAutoSyncIntervalMinutes,omitempty"`
	OutboundAutoSyncIncludeViolations      *bool                           `json:"outboundAutoSyncIncludeViolations,omitempty"`
	OutboundAutoSyncViolationThreshold     *int64                          `json:"outboundAutoSyncViolationThreshold,omitempty"`
	LowestProgressiveInboundPolicyStatus   *string                         `json:"lowestProgressiveInboundPolicyStatus,omitempty"`
	LowestProgressiveOutboundPolicyStatus  *string                         `json:"lowestProgressiveOutboundPolicyStatus,omitempty"`
	TemplatesAssigned                      *int64                          `json:"templatesAssigned,omitempty"`
	NamednetworksAssigned                  *int64                          `json:"namednetworksAssigned,omitempty"`
	AllowTemplatesAssigned                 *int64                          `json:"allowTemplatesAssigned,omitempty"`
	BlockTemplatesAssigned                 *int64                          `json:"blockTemplatesAssigned,omitempty"`
	ActiveBreachModeTemplatesAssigned      *int64                          `json:"activeBreachModeTemplatesAssigned,omitempty"`
}

func (o *TagBasedPolicyResponse) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *TagBasedPolicyResponse) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *TagBasedPolicyResponse) GetTagBasedPolicyName() *string {
	if o == nil {
		return nil
	}
	return o.TagBasedPolicyName
}

func (o *TagBasedPolicyResponse) GetTargetBreachImpactScore() *int64 {
	if o == nil {
		return nil
	}
	return o.TargetBreachImpactScore
}

func (o *TagBasedPolicyResponse) GetTimeline() *int64 {
	if o == nil {
		return nil
	}
	return o.Timeline
}

func (o *TagBasedPolicyResponse) GetCriteria() *string {
	if o == nil {
		return nil
	}
	return o.Criteria
}

func (o *TagBasedPolicyResponse) GetNamednetworks() []MetadataNamedNetworkReference {
	if o == nil {
		return nil
	}
	return o.Namednetworks
}

func (o *TagBasedPolicyResponse) GetTemplates() []TemplateReference {
	if o == nil {
		return nil
	}
	return o.Templates
}

func (o *TagBasedPolicyResponse) GetMilestones() []TagBasedPolicyMilestone {
	if o == nil {
		return nil
	}
	return o.Milestones
}

func (o *TagBasedPolicyResponse) GetMatchingAssets() *int64 {
	if o == nil {
		return nil
	}
	return o.MatchingAssets
}

func (o *TagBasedPolicyResponse) GetBaselineBreachImpactScore() *int64 {
	if o == nil {
		return nil
	}
	return o.BaselineBreachImpactScore
}

func (o *TagBasedPolicyResponse) GetBaselineMatchingAssets() *int64 {
	if o == nil {
		return nil
	}
	return o.BaselineMatchingAssets
}

func (o *TagBasedPolicyResponse) GetPolicyAutomationConfigurable() *bool {
	if o == nil {
		return nil
	}
	return o.PolicyAutomationConfigurable
}

func (o *TagBasedPolicyResponse) GetLowestInboundSegmentAssetPolicyStatus() *string {
	if o == nil {
		return nil
	}
	return o.LowestInboundSegmentAssetPolicyStatus
}

func (o *TagBasedPolicyResponse) GetLowestOutboundSegmentAssetPolicyStatus() *string {
	if o == nil {
		return nil
	}
	return o.LowestOutboundSegmentAssetPolicyStatus
}

func (o *TagBasedPolicyResponse) GetInboundAutoSyncDeploymentMode() *string {
	if o == nil {
		return nil
	}
	return o.InboundAutoSyncDeploymentMode
}

func (o *TagBasedPolicyResponse) GetInboundAutoSyncIntervalMinutes() *int64 {
	if o == nil {
		return nil
	}
	return o.InboundAutoSyncIntervalMinutes
}

func (o *TagBasedPolicyResponse) GetInboundAutoSyncIncludeViolations() *bool {
	if o == nil {
		return nil
	}
	return o.InboundAutoSyncIncludeViolations
}

func (o *TagBasedPolicyResponse) GetInboundAutoSyncViolationThreshold() *int64 {
	if o == nil {
		return nil
	}
	return o.InboundAutoSyncViolationThreshold
}

func (o *TagBasedPolicyResponse) GetOutboundAutoSyncDeploymentMode() *string {
	if o == nil {
		return nil
	}
	return o.OutboundAutoSyncDeploymentMode
}

func (o *TagBasedPolicyResponse) GetOutboundAutoSyncIntervalMinutes() *int64 {
	if o == nil {
		return nil
	}
	return o.OutboundAutoSyncIntervalMinutes
}

func (o *TagBasedPolicyResponse) GetOutboundAutoSyncIncludeViolations() *bool {
	if o == nil {
		return nil
	}
	return o.OutboundAutoSyncIncludeViolations
}

func (o *TagBasedPolicyResponse) GetOutboundAutoSyncViolationThreshold() *int64 {
	if o == nil {
		return nil
	}
	return o.OutboundAutoSyncViolationThreshold
}

func (o *TagBasedPolicyResponse) GetLowestProgressiveInboundPolicyStatus() *string {
	if o == nil {
		return nil
	}
	return o.LowestProgressiveInboundPolicyStatus
}

func (o *TagBasedPolicyResponse) GetLowestProgressiveOutboundPolicyStatus() *string {
	if o == nil {
		return nil
	}
	return o.LowestProgressiveOutboundPolicyStatus
}

func (o *TagBasedPolicyResponse) GetTemplatesAssigned() *int64 {
	if o == nil {
		return nil
	}
	return o.TemplatesAssigned
}

func (o *TagBasedPolicyResponse) GetNamednetworksAssigned() *int64 {
	if o == nil {
		return nil
	}
	return o.NamednetworksAssigned
}

func (o *TagBasedPolicyResponse) GetAllowTemplatesAssigned() *int64 {
	if o == nil {
		return nil
	}
	return o.AllowTemplatesAssigned
}

func (o *TagBasedPolicyResponse) GetBlockTemplatesAssigned() *int64 {
	if o == nil {
		return nil
	}
	return o.BlockTemplatesAssigned
}

func (o *TagBasedPolicyResponse) GetActiveBreachModeTemplatesAssigned() *int64 {
	if o == nil {
		return nil
	}
	return o.ActiveBreachModeTemplatesAssigned
}

func (o *TagBasedPolicyResponse) GetCriteriaAsParams() *string {
	if o == nil {
		return nil
	}
	return o.CriteriaAsParams
}
