// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"time"

	"github.com/colortokens/terraform-provider-xshield/internal/sdk/internal/utils"
)

type TagBasedPolicySummary struct {
	AutoSynchronizeEnabled               *bool      `json:"autoSynchronizeEnabled,omitempty"`
	Criteria                             *string    `json:"criteria,omitempty"`
	Description                          *string    `json:"description,omitempty"`
	LowestInboundPolicyStatus            *string    `json:"lowestInboundPolicyStatus,omitempty"`
	LowestOutboundPolicyStatus           *string    `json:"lowestOutboundPolicyStatus,omitempty"`
	LowestProgressiveInboundPolicyStatus *string    `json:"lowestProgressiveInboundPolicyStatus,omitempty"`
	MatchingAssets                       *int64     `json:"matchingAssets,omitempty"`
	NamednetworksAssigned                *int64     `json:"namednetworksAssigned,omitempty"`
	PolicyAutomationConfigurable         *bool      `json:"policyAutomationConfigurable,omitempty"`
	PolicyProgressiveLastRefreshed       *time.Time `json:"policyProgressiveLastRefreshed,omitempty"`
	TagBasedPolicyID                     *string    `json:"tagBasedPolicyId,omitempty"`
	TagBasedPolicyName                   *string    `json:"tagBasedPolicyName,omitempty"`
	TemplatesAssigned                    *int64     `json:"templatesAssigned,omitempty"`
}

func (t TagBasedPolicySummary) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TagBasedPolicySummary) UnmarshalJSON(data []byte) error {
	// Create a temporary struct with string for time fields
	type TempStruct struct {
		AutoSynchronizeEnabled               *bool   `json:"autoSynchronizeEnabled,omitempty"`
		Criteria                             *string `json:"criteria,omitempty"`
		Description                          *string `json:"description,omitempty"`
		LowestInboundPolicyStatus            *string `json:"lowestInboundPolicyStatus,omitempty"`
		LowestOutboundPolicyStatus           *string `json:"lowestOutboundPolicyStatus,omitempty"`
		LowestProgressiveInboundPolicyStatus *string `json:"lowestProgressiveInboundPolicyStatus,omitempty"`
		MatchingAssets                       *int64  `json:"matchingAssets,omitempty"`
		NamednetworksAssigned                *int64  `json:"namednetworksAssigned,omitempty"`
		PolicyAutomationConfigurable         *bool   `json:"policyAutomationConfigurable,omitempty"`
		PolicyProgressiveLastRefreshed       *string `json:"policyProgressiveLastRefreshed,omitempty"`
		TagBasedPolicyID                     *string `json:"tagBasedPolicyId,omitempty"`
		TagBasedPolicyName                   *string `json:"tagBasedPolicyName,omitempty"`
		TemplatesAssigned                    *int64  `json:"templatesAssigned,omitempty"`
	}

	// Unmarshal into the temporary struct
	var temp TempStruct
	if err := utils.UnmarshalJSON(data, &temp, "", false, false); err != nil {
		return err
	}

	// Copy the simple fields
	t.AutoSynchronizeEnabled = temp.AutoSynchronizeEnabled
	t.Criteria = temp.Criteria
	t.Description = temp.Description
	t.LowestInboundPolicyStatus = temp.LowestInboundPolicyStatus
	t.LowestOutboundPolicyStatus = temp.LowestOutboundPolicyStatus
	t.LowestProgressiveInboundPolicyStatus = temp.LowestProgressiveInboundPolicyStatus
	t.MatchingAssets = temp.MatchingAssets
	t.NamednetworksAssigned = temp.NamednetworksAssigned
	t.PolicyAutomationConfigurable = temp.PolicyAutomationConfigurable
	t.TagBasedPolicyID = temp.TagBasedPolicyID
	t.TagBasedPolicyName = temp.TagBasedPolicyName
	t.TemplatesAssigned = temp.TemplatesAssigned

	// Handle the time field specially
	if temp.PolicyProgressiveLastRefreshed != nil && *temp.PolicyProgressiveLastRefreshed != "" {
		parsedTime, err := time.Parse(time.RFC3339, *temp.PolicyProgressiveLastRefreshed)
		if err != nil {
			return err
		}
		t.PolicyProgressiveLastRefreshed = &parsedTime
	}

	return nil
}

func (o *TagBasedPolicySummary) GetAutoSynchronizeEnabled() *bool {
	if o == nil {
		return nil
	}
	return o.AutoSynchronizeEnabled
}

func (o *TagBasedPolicySummary) GetCriteria() *string {
	if o == nil {
		return nil
	}
	return o.Criteria
}

func (o *TagBasedPolicySummary) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *TagBasedPolicySummary) GetLowestInboundPolicyStatus() *string {
	if o == nil {
		return nil
	}
	return o.LowestInboundPolicyStatus
}

func (o *TagBasedPolicySummary) GetLowestOutboundPolicyStatus() *string {
	if o == nil {
		return nil
	}
	return o.LowestOutboundPolicyStatus
}

func (o *TagBasedPolicySummary) GetLowestProgressiveInboundPolicyStatus() *string {
	if o == nil {
		return nil
	}
	return o.LowestProgressiveInboundPolicyStatus
}

func (o *TagBasedPolicySummary) GetMatchingAssets() *int64 {
	if o == nil {
		return nil
	}
	return o.MatchingAssets
}

func (o *TagBasedPolicySummary) GetNamednetworksAssigned() *int64 {
	if o == nil {
		return nil
	}
	return o.NamednetworksAssigned
}

func (o *TagBasedPolicySummary) GetPolicyAutomationConfigurable() *bool {
	if o == nil {
		return nil
	}
	return o.PolicyAutomationConfigurable
}

func (o *TagBasedPolicySummary) GetPolicyProgressiveLastRefreshed() *time.Time {
	if o == nil {
		return nil
	}
	return o.PolicyProgressiveLastRefreshed
}

func (o *TagBasedPolicySummary) GetTagBasedPolicyID() *string {
	if o == nil {
		return nil
	}
	return o.TagBasedPolicyID
}

func (o *TagBasedPolicySummary) GetTagBasedPolicyName() *string {
	if o == nil {
		return nil
	}
	return o.TagBasedPolicyName
}

func (o *TagBasedPolicySummary) GetTemplatesAssigned() *int64 {
	if o == nil {
		return nil
	}
	return o.TemplatesAssigned
}
