// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"time"
)

type TagBasedPolicyMilestone struct {
	CompletedAt          *SafeTime `json:"completedAt,omitempty"`
	CompletionPercentage *float64  `json:"completionPercentage,omitempty"`
	MilestoneID          *int64    `json:"milestoneId,omitempty"`
	Name                 *string   `json:"name,omitempty"`
	StartedAt            *SafeTime `json:"startedAt,omitempty"`
	TargetDate           *SafeTime `json:"targetDate,omitempty"`
}

func (o *TagBasedPolicyMilestone) GetCompletionPercentage() *float64 {
	if o == nil {
		return nil
	}
	return o.CompletionPercentage
}

func (o *TagBasedPolicyMilestone) GetMilestoneID() *int64 {
	if o == nil {
		return nil
	}
	return o.MilestoneID
}

func (o *TagBasedPolicyMilestone) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *TagBasedPolicyMilestone) GetCompletedAt() *time.Time {
	if o == nil || o.CompletedAt == nil {
		return nil
	}
	t := o.CompletedAt.Time
	return &t
}

func (o *TagBasedPolicyMilestone) GetStartedAt() *time.Time {
	if o == nil || o.StartedAt == nil {
		return nil
	}
	t := o.StartedAt.Time
	return &t
}

func (o *TagBasedPolicyMilestone) GetTargetDate() *time.Time {
	if o == nil || o.TargetDate == nil {
		return nil
	}
	t := o.TargetDate.Time
	return &t
}
