// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// TagsBasedPolicyAutomationConfig represents the request body for the automation configuration API
type TagsBasedPolicyAutomationConfig struct {
	InboundAutoSyncDeploymentMode     *AutoDeploymentMode `json:"inboundAutoSyncDeploymentMode,omitempty"`
	InboundAutoSyncIncludeViolations  *bool               `json:"inboundAutoSyncIncludeViolations,omitempty"`
	InboundAutoSyncIntervalMinutes    *int64              `json:"inboundAutoSyncIntervalMinutes,omitempty"`
	InboundAutoSyncViolationThreshold *int64              `json:"inboundAutoSyncViolationThreshold,omitempty"`

	LowestInboundSegmentAssetPolicyStatus  *string `json:"lowestInboundSegmentAssetPolicyStatus,omitempty"`
	LowestOutboundSegmentAssetPolicyStatus *string `json:"lowestOutboundSegmentAssetPolicyStatus,omitempty"`

	OutboundAutoSyncDeploymentMode     *AutoDeploymentMode `json:"outboundAutoSyncDeploymentMode,omitempty"`
	OutboundAutoSyncIncludeViolations  *bool               `json:"outboundAutoSyncIncludeViolations,omitempty"`
	OutboundAutoSyncIntervalMinutes    *int64              `json:"outboundAutoSyncIntervalMinutes,omitempty"`
	OutboundAutoSyncViolationThreshold *int64              `json:"outboundAutoSyncViolationThreshold,omitempty"`
}
