// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type TemplateRuleHitMetrics struct {
	LastEvaluated *string `json:"lastEvaluated,omitempty"`
	TotalHits     *string `json:"totalHits,omitempty"`
}

func (o *TemplateRuleHitMetrics) GetLastEvaluated() *string {
	if o == nil {
		return nil
	}
	return o.LastEvaluated
}

func (o *TemplateRuleHitMetrics) GetTotalHits() *string {
	if o == nil {
		return nil
	}
	return o.TotalHits
}
