// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// TemplateList - List of template IDs
type TemplateList struct {
	// Optional comment
	Comment *string `json:"comment,omitempty"`
	// List of template IDs
	Templates []string `json:"templates"`
}
