// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"time"
)

type TemplateType string

const (
	TemplateTypeApplicationTemplate TemplateType = "application-template"
	TemplateTypeBlockTemplate       TemplateType = "block-template"
)

func (e TemplateType) ToPointer() *TemplateType {
	return &e
}
func (e *TemplateType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "application-template":
		fallthrough
	case "block-template":
		*e = TemplateType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for TemplateType: %v", v)
	}
}

// SafeTime is a wrapper around time.Time that handles empty string values in JSON
type SafeTime struct {
	time.Time
}

// UnmarshalJSON implements the json.Unmarshaler interface for SafeTime
func (st *SafeTime) UnmarshalJSON(data []byte) error {
	s := string(data)

	// Handle empty strings and null values
	if s == "\"\"" || s == "null" || s == "" {
		// Return without error, leaving the time as zero value
		return nil
	}

	// Try to unmarshal as a string
	var timeStr string
	if err := json.Unmarshal(data, &timeStr); err != nil {
		return err
	}

	// Handle empty string
	if timeStr == "" {
		return nil
	}

	// Parse the time string
	t, err := time.Parse(time.RFC3339, timeStr)
	if err != nil {
		return err
	}

	st.Time = t
	return nil
}

type Template struct {
	AccessPolicyTemplate *bool          `json:"accessPolicyTemplate,omitempty"`
	CreatedAt            *SafeTime      `json:"createdAt,omitempty"`
	DeletedAt            *SafeTime      `json:"deletedAt,omitempty"`
	IsDeleted            *bool          `json:"isDeleted,omitempty"`
	ColortokensManaged   *bool          `json:"oobTemplate,omitempty"`
	TemplateBreachLevels []string       `json:"templateBreachLevels,omitempty"`
	TemplateCategory     *string        `json:"templateCategory,omitempty"`
	TemplateDescription  *string        `json:"templateDescription,omitempty"`
	ID                   *string        `json:"templateId,omitempty"`
	TemplateName         *string        `json:"templateName,omitempty"`
	TemplatePaths        []MetadataPath `json:"templatePaths,omitempty"`
	TemplatePorts        []MetadataPort `json:"templatePorts,omitempty"`
	TemplateType         *TemplateType  `json:"templateType,omitempty"`
}

func (o *Template) GetAccessPolicyTemplate() *bool {
	if o == nil {
		return nil
	}
	return o.AccessPolicyTemplate
}

func (o *Template) GetColortokensManaged() *bool {
	if o == nil {
		return nil
	}
	return o.ColortokensManaged
}

func (o *Template) GetCreatedAt() *time.Time {
	if o == nil || o.CreatedAt == nil {
		return nil
	}
	t := o.CreatedAt.Time
	return &t
}

func (o *Template) GetDeletedAt() *time.Time {
	if o == nil || o.DeletedAt == nil {
		return nil
	}
	t := o.DeletedAt.Time
	return &t
}

func (o *Template) GetIsDeleted() *bool {
	if o == nil {
		return nil
	}
	return o.IsDeleted
}

func (o *Template) GetTemplateBreachLevels() []string {
	if o == nil {
		return nil
	}
	return o.TemplateBreachLevels
}

func (o *Template) GetTemplateCategory() *string {
	if o == nil {
		return nil
	}
	return o.TemplateCategory
}

func (o *Template) GetTemplateDescription() *string {
	if o == nil {
		return nil
	}
	return o.TemplateDescription
}

func (o *Template) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *Template) GetTemplateName() *string {
	if o == nil {
		return nil
	}
	return o.TemplateName
}

func (o *Template) GetTemplatePaths() []MetadataPath {
	if o == nil {
		return nil
	}
	return o.TemplatePaths
}

func (o *Template) GetTemplatePorts() []MetadataPort {
	if o == nil {
		return nil
	}
	return o.TemplatePorts
}

func (o *Template) GetTemplateType() *TemplateType {
	if o == nil {
		return nil
	}
	return o.TemplateType
}
