// Code generated by scripts/gen_asset_provider.py from shared.AssetDetails.
// Re-run that script rather than editing by hand; see scripts/README.md.

package provider

import (
	"github.com/colortokens/terraform-provider-xshield/internal/sdk/models/shared"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

func (r *AssetResourceModel) RefreshFromSharedAssetDetails(resp *shared.AssetDetails) {
	if resp != nil {
		r.AgentID = types.StringPointerValue(resp.AgentID)
		r.ID = types.StringPointerValue(resp.ID)
		r.AssetName = types.StringValue(resp.AssetName)
		if len(resp.CoreTags) > 0 {
			r.CoreTags = make(map[string]types.String, len(resp.CoreTags))
			for k, v := range resp.CoreTags {
				r.CoreTags[k] = types.StringValue(v)
			}
		} else {
			r.CoreTags = nil
		}
		r.DeterministicID = types.StringPointerValue(resp.DeterministicID)
		r.Type = types.StringValue(resp.Type)
		r.VendorInfo = types.StringPointerValue(resp.VendorInfo)
		if resp.InboundAssetDeploymentState != nil {
			r.InboundEnforcement = types.BoolValue(*resp.InboundAssetDeploymentState == "enabled")
		} else {
			r.InboundEnforcement = types.BoolNull()
		}
		if resp.OutboundAssetDeploymentState != nil {
			r.OutboundEnforcement = types.BoolValue(*resp.OutboundAssetDeploymentState == "enabled")
		} else {
			r.OutboundEnforcement = types.BoolNull()
		}
	}
}

func (r *AssetResourceModel) ToSharedCreateAssetDetails() *shared.CreateAssetDetails {
	agentID := new(string)
	if !r.AgentID.IsUnknown() && !r.AgentID.IsNull() {
		*agentID = r.AgentID.ValueString()
	} else {
		agentID = nil
	}
	id := new(string)
	if !r.ID.IsUnknown() && !r.ID.IsNull() {
		*id = r.ID.ValueString()
	} else {
		id = nil
	}
	var assetName string
	assetName = r.AssetName.ValueString()

	var typeVar string
	typeVar = r.Type.ValueString()

	coreTags := make(map[string]string)
	for coreTagsKey, coreTagsValue := range r.CoreTags {
		var coreTagsInst string
		coreTagsInst = coreTagsValue.ValueString()

		coreTags[coreTagsKey] = coreTagsInst
	}
	deterministicID := new(string)
	if !r.DeterministicID.IsUnknown() && !r.DeterministicID.IsNull() {
		*deterministicID = r.DeterministicID.ValueString()
	} else {
		deterministicID = nil
	}
	vendorInfo := new(string)
	if !r.VendorInfo.IsUnknown() && !r.VendorInfo.IsNull() {
		*vendorInfo = r.VendorInfo.ValueString()
	} else {
		vendorInfo = nil
	}
	out := shared.CreateAssetDetails{
		AgentID:         agentID,
		ID:              id,
		AssetName:       assetName,
		Type:            typeVar,
		CoreTags:        coreTags,
		DeterministicID: deterministicID,
		VendorInfo:      vendorInfo,
	}
	return &out
}
