// Code generated by scripts/gen_asset_provider.py from shared.AssetDetails.
// Re-run that script rather than editing by hand; see scripts/README.md.

package provider

import (
	"time"

	tfTypes "github.com/colortokens/terraform-provider-xshield/internal/provider/types"
	"github.com/colortokens/terraform-provider-xshield/internal/sdk/models/shared"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

func (r *AssetDataSourceModel) RefreshFromSharedAssetDetails(resp *shared.AssetDetails) {
	if resp != nil {
		r.IPV6BlanketAllowStatus = types.StringPointerValue(resp.IPV6BlanketAllowStatus)
		r.ActiveBreachModeTemplatesAssigned = types.Int64PointerValue(resp.ActiveBreachModeTemplatesAssigned)
		r.AgentID = types.StringPointerValue(resp.AgentID)
		if resp.AgentLastCheckInTime != nil && !resp.AgentLastCheckInTime.Time.IsZero() {
			r.AgentLastCheckInTime = types.StringValue(resp.AgentLastCheckInTime.Time.Format(time.RFC3339))
		} else {
			r.AgentLastCheckInTime = types.StringNull()
		}
		r.AgentName = types.StringPointerValue(resp.AgentName)
		r.AgentStatus = types.StringPointerValue(resp.AgentStatus)
		r.AgentVersion = types.StringPointerValue(resp.AgentVersion)
		r.AllowTemplatesAssigned = types.Int64PointerValue(resp.AllowTemplatesAssigned)
		r.AppControlAssetDeploymentState = types.StringPointerValue(resp.AppControlAssetDeploymentState)
		if resp.AppControlAssetPendingChanges == nil {
			r.AppControlAssetPendingChanges = nil
		} else {
			r.AppControlAssetPendingChanges = &tfTypes.AppControlPendingChanges{}
			r.AppControlAssetPendingChanges.AllowTemplates = make([]types.String, 0, len(resp.AppControlAssetPendingChanges.AllowTemplates))
			for _, v := range resp.AppControlAssetPendingChanges.AllowTemplates {
				r.AppControlAssetPendingChanges.AllowTemplates = append(r.AppControlAssetPendingChanges.AllowTemplates, types.StringValue(v))
			}
			r.AppControlAssetPendingChanges.BlockTemplates = make([]types.String, 0, len(resp.AppControlAssetPendingChanges.BlockTemplates))
			for _, v := range resp.AppControlAssetPendingChanges.BlockTemplates {
				r.AppControlAssetPendingChanges.BlockTemplates = append(r.AppControlAssetPendingChanges.BlockTemplates, types.StringValue(v))
			}
			r.AppControlAssetPendingChanges.ChangedApplications = types.Int64PointerValue(resp.AppControlAssetPendingChanges.ChangedApplications)
		}
		r.AppControlAssetPolicyMode = types.StringPointerValue(resp.AppControlAssetPolicyMode)
		r.AppControlAssetPolicyStatus = types.StringPointerValue(resp.AppControlAssetPolicyStatus)
		if resp.AppControlAssetPolicyUpdatedAt != nil && !resp.AppControlAssetPolicyUpdatedAt.Time.IsZero() {
			r.AppControlAssetPolicyUpdatedAt = types.StringValue(resp.AppControlAssetPolicyUpdatedAt.Time.Format(time.RFC3339))
		} else {
			r.AppControlAssetPolicyUpdatedAt = types.StringNull()
		}
		r.AppControlAssetStatus = types.StringPointerValue(resp.AppControlAssetStatus)
		r.AppControlAutoSyncDeploymentMode = types.StringPointerValue(resp.AppControlAutoSyncDeploymentMode)
		r.AppControlAutoSyncIncludeViolations = types.BoolPointerValue(resp.AppControlAutoSyncIncludeViolations)
		r.AppControlAutoSyncIntervalMinutes = types.Int64PointerValue(resp.AppControlAutoSyncIntervalMinutes)
		r.AppControlAutoSyncViolationThreshold = types.Int64PointerValue(resp.AppControlAutoSyncViolationThreshold)
		if resp.AppControlLastRefreshed != nil && !resp.AppControlLastRefreshed.Time.IsZero() {
			r.AppControlLastRefreshed = types.StringValue(resp.AppControlLastRefreshed.Time.Format(time.RFC3339))
		} else {
			r.AppControlLastRefreshed = types.StringNull()
		}
		r.AssetAvailability = types.StringPointerValue(resp.AssetAvailability)
		r.ID = types.StringPointerValue(resp.ID)
		r.AssetInternetFacing = types.BoolPointerValue(resp.AssetInternetFacing)
		r.AssetName = types.StringValue(resp.AssetName)
		r.AssetRisk = types.StringPointerValue(resp.AssetRisk)
		r.AttackSurface = types.StringPointerValue(resp.AttackSurface)
		if resp.AttackSurfacePendingChanges == nil {
			r.AttackSurfacePendingChanges = nil
		} else {
			r.AttackSurfacePendingChanges = &tfTypes.PendingChanges{}
			r.AttackSurfacePendingChanges.AllowTemplates = make([]types.String, 0, len(resp.AttackSurfacePendingChanges.AllowTemplates))
			for _, v := range resp.AttackSurfacePendingChanges.AllowTemplates {
				r.AttackSurfacePendingChanges.AllowTemplates = append(r.AttackSurfacePendingChanges.AllowTemplates, types.StringValue(v))
			}
			r.AttackSurfacePendingChanges.AssetPolicySyncPending = types.BoolPointerValue(resp.AttackSurfacePendingChanges.AssetPolicySyncPending)
			r.AttackSurfacePendingChanges.BlockTemplates = make([]types.String, 0, len(resp.AttackSurfacePendingChanges.BlockTemplates))
			for _, v := range resp.AttackSurfacePendingChanges.BlockTemplates {
				r.AttackSurfacePendingChanges.BlockTemplates = append(r.AttackSurfacePendingChanges.BlockTemplates, types.StringValue(v))
			}
			r.AttackSurfacePendingChanges.InternetPaths = types.Int64PointerValue(resp.AttackSurfacePendingChanges.InternetPaths)
			r.AttackSurfacePendingChanges.InternetPorts = types.Int64PointerValue(resp.AttackSurfacePendingChanges.InternetPorts)
			r.AttackSurfacePendingChanges.IntranetPaths = types.Int64PointerValue(resp.AttackSurfacePendingChanges.IntranetPaths)
			r.AttackSurfacePendingChanges.IntranetPorts = types.Int64PointerValue(resp.AttackSurfacePendingChanges.IntranetPorts)
			r.AttackSurfacePendingChanges.NamednetworkChange = make([]types.String, 0, len(resp.AttackSurfacePendingChanges.NamednetworkChange))
			for _, v := range resp.AttackSurfacePendingChanges.NamednetworkChange {
				r.AttackSurfacePendingChanges.NamednetworkChange = append(r.AttackSurfacePendingChanges.NamednetworkChange, types.StringValue(v))
			}
			r.AttackSurfacePendingChanges.PeerChange = types.BoolPointerValue(resp.AttackSurfacePendingChanges.PeerChange)
			r.AttackSurfacePendingChanges.UnassignedAllowTemplates = make([]types.String, 0, len(resp.AttackSurfacePendingChanges.UnassignedAllowTemplates))
			for _, v := range resp.AttackSurfacePendingChanges.UnassignedAllowTemplates {
				r.AttackSurfacePendingChanges.UnassignedAllowTemplates = append(r.AttackSurfacePendingChanges.UnassignedAllowTemplates, types.StringValue(v))
			}
			r.AttackSurfacePendingChanges.UnassignedBlockTemplates = make([]types.String, 0, len(resp.AttackSurfacePendingChanges.UnassignedBlockTemplates))
			for _, v := range resp.AttackSurfacePendingChanges.UnassignedBlockTemplates {
				r.AttackSurfacePendingChanges.UnassignedBlockTemplates = append(r.AttackSurfacePendingChanges.UnassignedBlockTemplates, types.StringValue(v))
			}
		}
		r.BlastRadius = types.StringPointerValue(resp.BlastRadius)
		if resp.BlastRadiusPendingChanges == nil {
			r.BlastRadiusPendingChanges = nil
		} else {
			r.BlastRadiusPendingChanges = &tfTypes.PendingChanges{}
			r.BlastRadiusPendingChanges.AllowTemplates = make([]types.String, 0, len(resp.BlastRadiusPendingChanges.AllowTemplates))
			for _, v := range resp.BlastRadiusPendingChanges.AllowTemplates {
				r.BlastRadiusPendingChanges.AllowTemplates = append(r.BlastRadiusPendingChanges.AllowTemplates, types.StringValue(v))
			}
			r.BlastRadiusPendingChanges.AssetPolicySyncPending = types.BoolPointerValue(resp.BlastRadiusPendingChanges.AssetPolicySyncPending)
			r.BlastRadiusPendingChanges.BlockTemplates = make([]types.String, 0, len(resp.BlastRadiusPendingChanges.BlockTemplates))
			for _, v := range resp.BlastRadiusPendingChanges.BlockTemplates {
				r.BlastRadiusPendingChanges.BlockTemplates = append(r.BlastRadiusPendingChanges.BlockTemplates, types.StringValue(v))
			}
			r.BlastRadiusPendingChanges.InternetPaths = types.Int64PointerValue(resp.BlastRadiusPendingChanges.InternetPaths)
			r.BlastRadiusPendingChanges.InternetPorts = types.Int64PointerValue(resp.BlastRadiusPendingChanges.InternetPorts)
			r.BlastRadiusPendingChanges.IntranetPaths = types.Int64PointerValue(resp.BlastRadiusPendingChanges.IntranetPaths)
			r.BlastRadiusPendingChanges.IntranetPorts = types.Int64PointerValue(resp.BlastRadiusPendingChanges.IntranetPorts)
			r.BlastRadiusPendingChanges.NamednetworkChange = make([]types.String, 0, len(resp.BlastRadiusPendingChanges.NamednetworkChange))
			for _, v := range resp.BlastRadiusPendingChanges.NamednetworkChange {
				r.BlastRadiusPendingChanges.NamednetworkChange = append(r.BlastRadiusPendingChanges.NamednetworkChange, types.StringValue(v))
			}
			r.BlastRadiusPendingChanges.PeerChange = types.BoolPointerValue(resp.BlastRadiusPendingChanges.PeerChange)
			r.BlastRadiusPendingChanges.UnassignedAllowTemplates = make([]types.String, 0, len(resp.BlastRadiusPendingChanges.UnassignedAllowTemplates))
			for _, v := range resp.BlastRadiusPendingChanges.UnassignedAllowTemplates {
				r.BlastRadiusPendingChanges.UnassignedAllowTemplates = append(r.BlastRadiusPendingChanges.UnassignedAllowTemplates, types.StringValue(v))
			}
			r.BlastRadiusPendingChanges.UnassignedBlockTemplates = make([]types.String, 0, len(resp.BlastRadiusPendingChanges.UnassignedBlockTemplates))
			for _, v := range resp.BlastRadiusPendingChanges.UnassignedBlockTemplates {
				r.BlastRadiusPendingChanges.UnassignedBlockTemplates = append(r.BlastRadiusPendingChanges.UnassignedBlockTemplates, types.StringValue(v))
			}
		}
		r.BlockCustomIPs = types.StringPointerValue(resp.BlockCustomIPs)
		r.BlockMaliciousIPs = types.StringPointerValue(resp.BlockMaliciousIPs)
		r.BlockTemplatesAssigned = types.Int64PointerValue(resp.BlockTemplatesAssigned)
		r.BreachResponseLevel = types.StringPointerValue(resp.BreachResponseLevel)
		r.BreachResponseModeSynced = types.StringPointerValue(resp.BreachResponseModeSynced)
		r.BusinessValue = types.StringPointerValue(resp.BusinessValue)
		r.CisaAdvisories = types.Int64PointerValue(resp.CisaAdvisories)
		r.CloudConnectorMode = types.StringPointerValue(resp.CloudConnectorMode)
		r.CloudTags = []tfTypes.Tag{}
		for _, v := range resp.CloudTags {
			var item tfTypes.Tag
			item.ID = types.StringPointerValue(v.ID)
			item.IsCloudTag = types.BoolPointerValue(v.IsCloudTag)
			item.Key = types.StringValue(v.Key)
			item.Value = types.StringValue(v.Value)
			r.CloudTags = append(r.CloudTags, item)
		}
		r.ClusterIdentifier = types.StringPointerValue(resp.ClusterIdentifier)
		r.ContainerNamespace = types.StringPointerValue(resp.ContainerNamespace)
		if len(resp.CoreTags) > 0 {
			r.CoreTags = make(map[string]types.String, len(resp.CoreTags))
			for k, v := range resp.CoreTags {
				r.CoreTags[k] = types.StringValue(v)
			}
		} else {
			r.CoreTags = nil
		}
		r.CPUCoreCount = types.Int64PointerValue(resp.CPUCoreCount)
		r.CPUName = types.StringPointerValue(resp.CPUName)
		if resp.CurrentTrafficConfiguration != nil {
			r.CurrentTrafficConfiguration = types.StringValue(string(*resp.CurrentTrafficConfiguration))
		} else {
			r.CurrentTrafficConfiguration = types.StringNull()
		}
		r.DeterministicID = types.StringPointerValue(resp.DeterministicID)
		r.DiskCapacityInGB = types.Int64PointerValue(resp.DiskCapacityInGB)
		r.FwCoexistenceCfgStatus = types.StringPointerValue(resp.FwCoexistenceCfgStatus)
		if resp.FwConfigPendingChanges == nil {
			r.FwConfigPendingChanges = nil
		} else {
			r.FwConfigPendingChanges = &tfTypes.FWConfigPendingChanges{}
			r.FwConfigPendingChanges.FwCoexistenceCfgUpdatePending = types.BoolPointerValue(resp.FwConfigPendingChanges.FwCoexistenceCfgUpdatePending)
			r.FwConfigPendingChanges.IntranetChange = types.BoolPointerValue(resp.FwConfigPendingChanges.IntranetChange)
			r.FwConfigPendingChanges.IPV6BlanketAllow = types.BoolPointerValue(resp.FwConfigPendingChanges.IPV6BlanketAllow)
		}
		r.HasInaccessibleSegments = types.BoolPointerValue(resp.HasInaccessibleSegments)
		r.HostName = types.StringPointerValue(resp.HostName)
		r.IamTemplatesAssigned = types.Int64PointerValue(resp.IamTemplatesAssigned)
		r.InboundAssetDeploymentState = types.StringPointerValue(resp.InboundAssetDeploymentState)
		if resp.InboundAssetPolicyLastRefreshed != nil && !resp.InboundAssetPolicyLastRefreshed.Time.IsZero() {
			r.InboundAssetPolicyLastRefreshed = types.StringValue(resp.InboundAssetPolicyLastRefreshed.Time.Format(time.RFC3339))
		} else {
			r.InboundAssetPolicyLastRefreshed = types.StringNull()
		}
		r.InboundAssetPolicyMode = types.StringPointerValue(resp.InboundAssetPolicyMode)
		r.InboundAssetPolicyStatus = types.StringPointerValue(resp.InboundAssetPolicyStatus)
		if resp.InboundAssetPolicyUpdatedAt != nil && !resp.InboundAssetPolicyUpdatedAt.Time.IsZero() {
			r.InboundAssetPolicyUpdatedAt = types.StringValue(resp.InboundAssetPolicyUpdatedAt.Time.Format(time.RFC3339))
		} else {
			r.InboundAssetPolicyUpdatedAt = types.StringNull()
		}
		r.InboundAssetStatus = types.StringPointerValue(resp.InboundAssetStatus)
		r.InboundAutoSyncDeploymentMode = types.StringPointerValue(resp.InboundAutoSyncDeploymentMode)
		r.InboundAutoSyncIncludeViolations = types.BoolPointerValue(resp.InboundAutoSyncIncludeViolations)
		r.InboundAutoSyncIntervalMinutes = types.Int64PointerValue(resp.InboundAutoSyncIntervalMinutes)
		r.InboundAutoSyncViolationThreshold = types.Int64PointerValue(resp.InboundAutoSyncViolationThreshold)
		if resp.InboundInternetPaths == nil {
			r.InboundInternetPaths = nil
		} else {
			r.InboundInternetPaths = &tfTypes.ReviewCoverage{}
			r.InboundInternetPaths.Allowed = types.Int64PointerValue(resp.InboundInternetPaths.Allowed)
			r.InboundInternetPaths.AllowedPorts = types.Int64PointerValue(resp.InboundInternetPaths.AllowedPorts)
			r.InboundInternetPaths.Reviewed = types.Int64PointerValue(resp.InboundInternetPaths.Reviewed)
			r.InboundInternetPaths.Total = types.Int64PointerValue(resp.InboundInternetPaths.Total)
			r.InboundInternetPaths.Unreviewed = types.Int64PointerValue(resp.InboundInternetPaths.Unreviewed)
		}
		if resp.InboundInternetPorts == nil {
			r.InboundInternetPorts = nil
		} else {
			r.InboundInternetPorts = &tfTypes.ReviewCoverage{}
			r.InboundInternetPorts.Allowed = types.Int64PointerValue(resp.InboundInternetPorts.Allowed)
			r.InboundInternetPorts.AllowedPorts = types.Int64PointerValue(resp.InboundInternetPorts.AllowedPorts)
			r.InboundInternetPorts.Reviewed = types.Int64PointerValue(resp.InboundInternetPorts.Reviewed)
			r.InboundInternetPorts.Total = types.Int64PointerValue(resp.InboundInternetPorts.Total)
			r.InboundInternetPorts.Unreviewed = types.Int64PointerValue(resp.InboundInternetPorts.Unreviewed)
		}
		if resp.InboundIntranetPaths == nil {
			r.InboundIntranetPaths = nil
		} else {
			r.InboundIntranetPaths = &tfTypes.ReviewCoverage{}
			r.InboundIntranetPaths.Allowed = types.Int64PointerValue(resp.InboundIntranetPaths.Allowed)
			r.InboundIntranetPaths.AllowedPorts = types.Int64PointerValue(resp.InboundIntranetPaths.AllowedPorts)
			r.InboundIntranetPaths.Reviewed = types.Int64PointerValue(resp.InboundIntranetPaths.Reviewed)
			r.InboundIntranetPaths.Total = types.Int64PointerValue(resp.InboundIntranetPaths.Total)
			r.InboundIntranetPaths.Unreviewed = types.Int64PointerValue(resp.InboundIntranetPaths.Unreviewed)
		}
		if resp.InboundIntranetPorts == nil {
			r.InboundIntranetPorts = nil
		} else {
			r.InboundIntranetPorts = &tfTypes.ReviewCoverage{}
			r.InboundIntranetPorts.Allowed = types.Int64PointerValue(resp.InboundIntranetPorts.Allowed)
			r.InboundIntranetPorts.AllowedPorts = types.Int64PointerValue(resp.InboundIntranetPorts.AllowedPorts)
			r.InboundIntranetPorts.Reviewed = types.Int64PointerValue(resp.InboundIntranetPorts.Reviewed)
			r.InboundIntranetPorts.Total = types.Int64PointerValue(resp.InboundIntranetPorts.Total)
			r.InboundIntranetPorts.Unreviewed = types.Int64PointerValue(resp.InboundIntranetPorts.Unreviewed)
		}
		r.Interfaces = []tfTypes.NetworkInterface{}
		for _, v := range resp.Interfaces {
			var item tfTypes.NetworkInterface
			item.Flags = make([]types.String, 0, len(v.Flags))
			for _, v := range v.Flags {
				item.Flags = append(item.Flags, types.StringValue(v))
			}
			item.Ipaddresses = make([]types.String, 0, len(v.Ipaddresses))
			for _, v := range v.Ipaddresses {
				item.Ipaddresses = append(item.Ipaddresses, types.StringValue(v))
			}
			item.Macaddress = types.StringPointerValue(v.Macaddress)
			item.Name = types.StringValue(v.Name)
			r.Interfaces = append(r.Interfaces, item)
		}
		r.IsFlowCollectorEdrType = types.BoolPointerValue(resp.IsFlowCollectorEdrType)
		r.KernelArchitecture = types.StringPointerValue(resp.KernelArchitecture)
		r.KernelVersion = types.StringPointerValue(resp.KernelVersion)
		r.LanInterfaceName = types.StringPointerValue(resp.LanInterfaceName)
		if resp.LastFWSynchronized != nil && !resp.LastFWSynchronized.Time.IsZero() {
			r.LastFWSynchronized = types.StringValue(resp.LastFWSynchronized.Time.Format(time.RFC3339))
		} else {
			r.LastFWSynchronized = types.StringNull()
		}
		if resp.LastPolicyDeploymentTriggeredAt != nil && !resp.LastPolicyDeploymentTriggeredAt.Time.IsZero() {
			r.LastPolicyDeploymentTriggeredAt = types.StringValue(resp.LastPolicyDeploymentTriggeredAt.Time.Format(time.RFC3339))
		} else {
			r.LastPolicyDeploymentTriggeredAt = types.StringNull()
		}
		r.LateralMovementAttacks = types.Int64PointerValue(resp.LateralMovementAttacks)
		r.LateralMovementTechniques = types.Int64PointerValue(resp.LateralMovementTechniques)
		r.LowestInboundAssetPolicyStatus = types.StringPointerValue(resp.LowestInboundAssetPolicyStatus)
		r.LowestOutboundAssetPolicyStatus = types.StringPointerValue(resp.LowestOutboundAssetPolicyStatus)
		r.ManagedBy = types.StringPointerValue(resp.ManagedBy)
		r.MicroDeploymentCompatible = types.BoolPointerValue(resp.MicroDeploymentCompatible)
		if resp.MostRecentNewPath != nil && !resp.MostRecentNewPath.Time.IsZero() {
			r.MostRecentNewPath = types.StringValue(resp.MostRecentNewPath.Time.Format(time.RFC3339))
		} else {
			r.MostRecentNewPath = types.StringNull()
		}
		r.NamedNetworkChanges = []tfTypes.MetadataNamedNetworkReference{}
		for _, v := range resp.NamedNetworkChanges {
			var item tfTypes.MetadataNamedNetworkReference
			item.NamedNetworkID = types.StringPointerValue(v.NamedNetworkID)
			item.NamedNetworkName = types.StringPointerValue(v.NamedNetworkName)
			r.NamedNetworkChanges = append(r.NamedNetworkChanges, item)
		}
		r.NamednetworksAssigned = types.Int64PointerValue(resp.NamednetworksAssigned)
		r.NewPathProcessingStopped = types.BoolPointerValue(resp.NewPathProcessingStopped)
		r.OsName = types.StringPointerValue(resp.OsName)
		r.OutboundAssetDeploymentState = types.StringPointerValue(resp.OutboundAssetDeploymentState)
		if resp.OutboundAssetPolicyLastRefreshed != nil && !resp.OutboundAssetPolicyLastRefreshed.Time.IsZero() {
			r.OutboundAssetPolicyLastRefreshed = types.StringValue(resp.OutboundAssetPolicyLastRefreshed.Time.Format(time.RFC3339))
		} else {
			r.OutboundAssetPolicyLastRefreshed = types.StringNull()
		}
		r.OutboundAssetPolicyMode = types.StringPointerValue(resp.OutboundAssetPolicyMode)
		r.OutboundAssetPolicyStatus = types.StringPointerValue(resp.OutboundAssetPolicyStatus)
		if resp.OutboundAssetPolicyUpdatedAt != nil && !resp.OutboundAssetPolicyUpdatedAt.Time.IsZero() {
			r.OutboundAssetPolicyUpdatedAt = types.StringValue(resp.OutboundAssetPolicyUpdatedAt.Time.Format(time.RFC3339))
		} else {
			r.OutboundAssetPolicyUpdatedAt = types.StringNull()
		}
		r.OutboundAssetStatus = types.StringPointerValue(resp.OutboundAssetStatus)
		r.OutboundAutoSyncDeploymentMode = types.StringPointerValue(resp.OutboundAutoSyncDeploymentMode)
		r.OutboundAutoSyncIncludeViolations = types.BoolPointerValue(resp.OutboundAutoSyncIncludeViolations)
		r.OutboundAutoSyncIntervalMinutes = types.Int64PointerValue(resp.OutboundAutoSyncIntervalMinutes)
		r.OutboundAutoSyncViolationThreshold = types.Int64PointerValue(resp.OutboundAutoSyncViolationThreshold)
		if resp.OutboundInternetPaths == nil {
			r.OutboundInternetPaths = nil
		} else {
			r.OutboundInternetPaths = &tfTypes.ReviewCoverage{}
			r.OutboundInternetPaths.Allowed = types.Int64PointerValue(resp.OutboundInternetPaths.Allowed)
			r.OutboundInternetPaths.AllowedPorts = types.Int64PointerValue(resp.OutboundInternetPaths.AllowedPorts)
			r.OutboundInternetPaths.Reviewed = types.Int64PointerValue(resp.OutboundInternetPaths.Reviewed)
			r.OutboundInternetPaths.Total = types.Int64PointerValue(resp.OutboundInternetPaths.Total)
			r.OutboundInternetPaths.Unreviewed = types.Int64PointerValue(resp.OutboundInternetPaths.Unreviewed)
		}
		if resp.OutboundIntranetPaths == nil {
			r.OutboundIntranetPaths = nil
		} else {
			r.OutboundIntranetPaths = &tfTypes.ReviewCoverage{}
			r.OutboundIntranetPaths.Allowed = types.Int64PointerValue(resp.OutboundIntranetPaths.Allowed)
			r.OutboundIntranetPaths.AllowedPorts = types.Int64PointerValue(resp.OutboundIntranetPaths.AllowedPorts)
			r.OutboundIntranetPaths.Reviewed = types.Int64PointerValue(resp.OutboundIntranetPaths.Reviewed)
			r.OutboundIntranetPaths.Total = types.Int64PointerValue(resp.OutboundIntranetPaths.Total)
			r.OutboundIntranetPaths.Unreviewed = types.Int64PointerValue(resp.OutboundIntranetPaths.Unreviewed)
		}
		r.PendingAppControlChanges = types.BoolPointerValue(resp.PendingAppControlChanges)
		r.PendingAttackSurfaceChanges = types.BoolPointerValue(resp.PendingAttackSurfaceChanges)
		r.PendingBlastRadiusChanges = types.BoolPointerValue(resp.PendingBlastRadiusChanges)
		r.PendingFWCoexistenceUpdateChanges = types.BoolPointerValue(resp.PendingFWCoexistenceUpdateChanges)
		r.PendingFWConfigChanges = types.BoolPointerValue(resp.PendingFWConfigChanges)
		r.Platform = types.StringPointerValue(resp.Platform)
		r.PoliciesAssigned = types.Int64PointerValue(resp.PoliciesAssigned)
		r.PolicyStatus = types.StringPointerValue(resp.PolicyStatus)
		r.Programs = []tfTypes.Program{}
		for _, v := range resp.Programs {
			var item tfTypes.Program
			item.Image = types.StringPointerValue(v.Image)
			item.Name = types.StringValue(v.Name)
			item.Path = types.StringPointerValue(v.Path)
			r.Programs = append(r.Programs, item)
		}
		r.RAMCapacityInMB = types.Int64PointerValue(resp.RAMCapacityInMB)
		r.RuleSynchronizeStatus = types.StringPointerValue(resp.RuleSynchronizeStatus)
		r.SecurityPatches = types.Int64PointerValue(resp.SecurityPatches)
		r.SerialNumber = types.StringPointerValue(resp.SerialNumber)
		r.Tags = []tfTypes.Tag{}
		for _, v := range resp.Tags {
			var item tfTypes.Tag
			item.ID = types.StringPointerValue(v.ID)
			item.IsCloudTag = types.BoolPointerValue(v.IsCloudTag)
			item.Key = types.StringValue(v.Key)
			item.Value = types.StringValue(v.Value)
			r.Tags = append(r.Tags, item)
		}
		r.TemplateChanges = []tfTypes.TemplateReference{}
		for _, v := range resp.TemplateChanges {
			var item tfTypes.TemplateReference
			item.TemplateID = types.StringPointerValue(v.TemplateID)
			item.TemplateName = types.StringPointerValue(v.TemplateName)
			r.TemplateChanges = append(r.TemplateChanges, item)
		}
		r.TemplatesAssigned = types.Int64PointerValue(resp.TemplatesAssigned)
		r.TotalBreachResponseComments = types.Int64PointerValue(resp.TotalBreachResponseComments)
		r.TotalComments = types.Int64PointerValue(resp.TotalComments)
		r.TotalInboundComments = types.Int64PointerValue(resp.TotalInboundComments)
		r.TotalOutboundComments = types.Int64PointerValue(resp.TotalOutboundComments)
		r.TotalPaths = types.Int64PointerValue(resp.TotalPaths)
		r.TotalPorts = types.Int64PointerValue(resp.TotalPorts)
		r.TotalPortsPathRestricted = types.Int64PointerValue(resp.TotalPortsPathRestricted)
		r.Type = types.StringValue(resp.Type)
		r.UnreviewedPaths = types.Int64PointerValue(resp.UnreviewedPaths)
		r.UnreviewedPorts = types.Int64PointerValue(resp.UnreviewedPorts)
		if resp.UsergroupMostRecentNewPath != nil && !resp.UsergroupMostRecentNewPath.Time.IsZero() {
			r.UsergroupMostRecentNewPath = types.StringValue(resp.UsergroupMostRecentNewPath.Time.Format(time.RFC3339))
		} else {
			r.UsergroupMostRecentNewPath = types.StringNull()
		}
		if resp.UsergroupOutboundInternetPaths == nil {
			r.UsergroupOutboundInternetPaths = nil
		} else {
			r.UsergroupOutboundInternetPaths = &tfTypes.ReviewCoverage{}
			r.UsergroupOutboundInternetPaths.Allowed = types.Int64PointerValue(resp.UsergroupOutboundInternetPaths.Allowed)
			r.UsergroupOutboundInternetPaths.AllowedPorts = types.Int64PointerValue(resp.UsergroupOutboundInternetPaths.AllowedPorts)
			r.UsergroupOutboundInternetPaths.Reviewed = types.Int64PointerValue(resp.UsergroupOutboundInternetPaths.Reviewed)
			r.UsergroupOutboundInternetPaths.Total = types.Int64PointerValue(resp.UsergroupOutboundInternetPaths.Total)
			r.UsergroupOutboundInternetPaths.Unreviewed = types.Int64PointerValue(resp.UsergroupOutboundInternetPaths.Unreviewed)
		}
		if resp.UsergroupOutboundIntranetPaths == nil {
			r.UsergroupOutboundIntranetPaths = nil
		} else {
			r.UsergroupOutboundIntranetPaths = &tfTypes.ReviewCoverage{}
			r.UsergroupOutboundIntranetPaths.Allowed = types.Int64PointerValue(resp.UsergroupOutboundIntranetPaths.Allowed)
			r.UsergroupOutboundIntranetPaths.AllowedPorts = types.Int64PointerValue(resp.UsergroupOutboundIntranetPaths.AllowedPorts)
			r.UsergroupOutboundIntranetPaths.Reviewed = types.Int64PointerValue(resp.UsergroupOutboundIntranetPaths.Reviewed)
			r.UsergroupOutboundIntranetPaths.Total = types.Int64PointerValue(resp.UsergroupOutboundIntranetPaths.Total)
			r.UsergroupOutboundIntranetPaths.Unreviewed = types.Int64PointerValue(resp.UsergroupOutboundIntranetPaths.Unreviewed)
		}
		r.UsergroupTotalPaths = types.Int64PointerValue(resp.UsergroupTotalPaths)
		r.UsergroupUnreviewedPaths = types.Int64PointerValue(resp.UsergroupUnreviewedPaths)
		r.Usergroups = []tfTypes.AssetGroup{}
		for _, v := range resp.Usergroups {
			var item tfTypes.AssetGroup
			item.Groupid = types.StringPointerValue(v.Groupid)
			r.Usergroups = append(r.Usergroups, item)
		}
		r.Users = []tfTypes.AssetUser{}
		for _, v := range resp.Users {
			var item tfTypes.AssetUser
			item.Assetid = types.StringValue(v.Assetid)
			item.Domainname = types.StringValue(v.Domainname)
			item.Email = types.StringPointerValue(v.Email)
			item.Logincount = types.Int64PointerValue(v.Logincount)
			item.Name = types.StringValue(v.Name)
			item.Scimuserid = types.StringPointerValue(v.Scimuserid)
			item.Signedin = types.BoolPointerValue(v.Signedin)
			r.Users = append(r.Users, item)
		}
		r.VendorInfo = types.StringPointerValue(resp.VendorInfo)
		r.VirtualizationSystem = types.StringPointerValue(resp.VirtualizationSystem)
		r.Vulnerabilities = types.Int64PointerValue(resp.Vulnerabilities)
		if resp.InboundAssetDeploymentState != nil {
			r.InboundEnforcement = types.BoolValue(*resp.InboundAssetDeploymentState == "enabled")
		} else {
			r.InboundEnforcement = types.BoolNull()
		}
		if resp.OutboundAssetDeploymentState != nil {
			r.OutboundEnforcement = types.BoolValue(*resp.OutboundAssetDeploymentState == "enabled")
		} else {
			r.OutboundEnforcement = types.BoolNull()
		}
	}
}
