// Code originally generated by Speakeasy (https://www.speakeasyapi.dev).

package provider

import (
	"context"
	"fmt"

	"github.com/colortokens/terraform-provider-xshield/internal/sdk"
	"github.com/colortokens/terraform-provider-xshield/internal/sdk/models/operations"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &AssetResource{}
var _ resource.ResourceWithImportState = &AssetResource{}

func NewAssetResource() resource.Resource {
	return &AssetResource{}
}

// AssetResource defines the resource implementation.
type AssetResource struct {
	client *sdk.Xshield
}

// AssetResourceModel describes the resource data model.
type AssetResourceModel struct {
	AgentID             types.String            `tfsdk:"agent_id"`
	ID                  types.String            `tfsdk:"id"`
	AssetName           types.String            `tfsdk:"asset_name"`
	CoreTags            map[string]types.String `tfsdk:"core_tags"`
	DeterministicID     types.String            `tfsdk:"deterministic_id"`
	Type                types.String            `tfsdk:"type"`
	VendorInfo          types.String            `tfsdk:"vendor_info"`
	InboundEnforcement  types.Bool              `tfsdk:"inbound_enforcement"`
	OutboundEnforcement types.Bool              `tfsdk:"outbound_enforcement"`
}

func (r *AssetResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_asset"
}

func (r *AssetResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "An asset under management: its name, type, core tags, and whether " +
			"policy is enforced in each direction.\n\n" +
			"**Assets cannot be created through Terraform.** They are registered by the agent. " +
			"Import one with `terraform import xshield_asset.example \"<asset name or id>\"`, then " +
			"manage it here.\n\n" +
			"This resource deliberately holds only what Terraform manages. Everything else the " +
			"platform knows about an asset, including its policy status, deployment states, risk " +
			"scores, open ports and paths, agent details, hardware inventory and derived tags, is " +
			"read through the `xshield_asset` data source, or `xshield_assets` to search across the " +
			"tenant. Those values change on their own as the agent checks in and the backend " +
			"recomputes, so keeping them out of resource state is what stops every plan from " +
			"reporting drift that no configuration change can resolve.",
		Attributes: map[string]schema.Attribute{
			"agent_id": schema.StringAttribute{
				Computed: true,
			},
			"id": schema.StringAttribute{
				Computed:    true,
				Description: `The asset's UUID, assigned by the platform. Either this or the asset's name works as the terraform import identifier.`,
			},
			"asset_name": schema.StringAttribute{
				Required:    true,
				Description: `The asset's name.`,
			},
			"core_tags": schema.MapAttribute{
				Optional:    true,
				ElementType: types.StringType,
			},
			"deterministic_id": schema.StringAttribute{
				Computed: true,
			},
			"type": schema.StringAttribute{
				Required: true,
			},
			"vendor_info": schema.StringAttribute{
				Computed: true,
			},
			"inbound_enforcement": schema.BoolAttribute{
				Optional:    true,
				Computed:    true,
				Description: `Whether inbound policy is enforced on this asset. Setting it calls the zero-trust endpoint; the deployed rules themselves come from templates and a deployment. Leave unset to leave the current state alone. Reported back from inbound_asset_deployment_state.`,
			},
			"outbound_enforcement": schema.BoolAttribute{
				Optional:    true,
				Computed:    true,
				Description: `Whether outbound policy is enforced on this asset. Setting it calls the zero-trust endpoint; the deployed rules themselves come from templates and a deployment. Leave unset to leave the current state alone. Reported back from outbound_asset_deployment_state.`,
			},
		},
	}
}

func (r *AssetResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	// Prevent panic if the provider has not been configured.
	if req.ProviderData == nil {
		return
	}

	providerData, ok := req.ProviderData.(*sdk.Xshield)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *sdk.Xshield, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)
		return
	}

	r.client = providerData
}

// ModifyPlan prevents asset creation through Terraform
func (r *AssetResource) ModifyPlan(ctx context.Context, req resource.ModifyPlanRequest, resp *resource.ModifyPlanResponse) {
	// Check if this is a create operation (prior state is null)
	var priorStateIsNull bool

	if req.State.Raw.IsNull() {
		priorStateIsNull = true
	}

	// If this is a create operation (no prior state), return an error
	if priorStateIsNull {
		resp.Diagnostics.AddError(
			"Asset creation not supported",
			"Assets cannot be created through Terraform. Please import an existing asset using 'terraform import' and then manage it with Terraform.",
		)
		return
	}
}

func (r *AssetResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	// Assets cannot be created through Terraform, only imported and then updated
	resp.Diagnostics.AddError(
		"Asset creation not supported",
		"Assets cannot be created through Terraform. Please import an existing asset using 'terraform import' and then manage it with Terraform.",
	)
}

func (r *AssetResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data *AssetResourceModel
	var item types.Object

	resp.Diagnostics.Append(req.State.Get(ctx, &item)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(item.As(ctx, &data, basetypes.ObjectAsOptions{
		UnhandledNullAsEmpty:    true,
		UnhandledUnknownAsEmpty: true,
	})...)

	if resp.Diagnostics.HasError() {
		return
	}

	assetID := data.ID.ValueString()

	request := operations.GetAssetRequest{
		AssetID: assetID,
	}
	res, err := r.client.Assets.GetAsset(ctx, request)
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", err.Error())
		if res != nil && res.RawResponse != nil {
			resp.Diagnostics.AddError("unexpected http request/response", debugResponse(res.RawResponse))
		}
		return
	}
	if res == nil {
		resp.Diagnostics.AddError("unexpected response from API", fmt.Sprintf("%v", res))
		return
	}
	if res.StatusCode == 404 {
		resp.State.RemoveResource(ctx)
		return
	}
	if res.StatusCode != 200 {
		resp.Diagnostics.AddError(fmt.Sprintf("unexpected response from API. Got an unexpected response code %v", res.StatusCode), debugResponse(res.RawResponse))
		return
	}
	if !(res.AssetDetails != nil) {
		resp.Diagnostics.AddError("unexpected response from API. Got an unexpected response body", debugResponse(res.RawResponse))
		return
	}
	data.RefreshFromSharedAssetDetails(res.AssetDetails)

	// Save updated data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *AssetResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var data *AssetResourceModel
	var plan types.Object

	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	var priorState *AssetResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &priorState)...)
	if resp.Diagnostics.HasError() {
		return
	}

	merge(ctx, req, resp, &data)
	if resp.Diagnostics.HasError() {
		return
	}

	assetID := data.ID.ValueString()

	// Enforcement is a separate endpoint from the asset's own attributes, and it
	// has to run before the read-back so the state reflects the change.
	applyAssetEnforcement(ctx, r.client, assetID, data, priorState, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}

	createAssetDetails := *data.ToSharedCreateAssetDetails()
	request := operations.UpdateAssetRequest{
		AssetID:            assetID,
		CreateAssetDetails: createAssetDetails,
	}
	res, err := r.client.Assets.UpdateAsset(ctx, request)
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", err.Error())
		if res != nil && res.RawResponse != nil {
			resp.Diagnostics.AddError("unexpected http request/response", debugResponse(res.RawResponse))
		}
		return
	}
	if res == nil {
		resp.Diagnostics.AddError("unexpected response from API", fmt.Sprintf("%v", res))
		return
	}
	if res.StatusCode != 200 {
		resp.Diagnostics.AddError(fmt.Sprintf("unexpected response from API. Got an unexpected response code %v", res.StatusCode), debugResponse(res.RawResponse))
		return
	}
	if !(res.AssetDetails != nil) {
		resp.Diagnostics.AddError("unexpected response from API. Got an unexpected response body", debugResponse(res.RawResponse))
		return
	}
	data.RefreshFromSharedAssetDetails(res.AssetDetails)
	refreshPlan(ctx, plan, &data, resp.Diagnostics)

	// Save updated data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *AssetResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var data *AssetResourceModel
	var item types.Object

	resp.Diagnostics.Append(req.State.Get(ctx, &item)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(item.As(ctx, &data, basetypes.ObjectAsOptions{
		UnhandledNullAsEmpty:    true,
		UnhandledUnknownAsEmpty: true,
	})...)

	if resp.Diagnostics.HasError() {
		return
	}

	// Not Implemented; entity does not have a configured DELETE operation
}

func (r *AssetResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	id := req.ID
	if !isXshieldUUID(id) {
		found, err := findAssetIDByName(ctx, r.client, id)
		if err != nil {
			resp.Diagnostics.AddError("Cannot import asset by name", err.Error())
			return
		}
		id = found
	}
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), id)...)
}

// Helper to check if a string is a UUID
