// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	"fmt"

	tfTypes "github.com/colortokens/terraform-provider-xshield/internal/provider/types"
	"github.com/colortokens/terraform-provider-xshield/internal/sdk"
	"github.com/colortokens/terraform-provider-xshield/internal/sdk/models/operations"
	"github.com/colortokens/terraform-provider-xshield/internal/sdk/models/shared"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ datasource.DataSource = &NamedNetworkDataSource{}
var _ datasource.DataSourceWithConfigure = &NamedNetworkDataSource{}

func NewNamedNetworkDataSource() datasource.DataSource {
	return &NamedNetworkDataSource{}
}

// NamedNetworkDataSource is the data source implementation.
type NamedNetworkDataSource struct {
	client *sdk.Xshield
}

// NamedNetworkDataSourceModel describes the data model.
type NamedNetworkDataSourceModel struct {
	AssignedByTagBasedPolicy              types.Bool                  `tfsdk:"assigned_by_tag_based_policy"`
	ColortokensManaged                    types.Bool                  `tfsdk:"colortokens_managed"`
	Domain                                types.String                `tfsdk:"domain"`
	ID                                    types.String                `tfsdk:"id"`
	IPRanges                              []tfTypes.NamednetworkRange `tfsdk:"ip_ranges"`
	NamedNetworkAssignments               types.Int64                 `tfsdk:"named_network_assignments"`
	NamedNetworkDescription               types.String                `tfsdk:"named_network_description"`
	NamedNetworkName                      types.String                `tfsdk:"named_network_name"`
	NamednetworkTagBasedPolicyAssignments types.Int64                 `tfsdk:"namednetwork_tag_based_policy_assignments"`
	ProgramAsInternet                     types.Bool                  `tfsdk:"program_as_internet"`
	ProgramAsIntranet                     types.Bool                  `tfsdk:"program_as_intranet"`
	Region                                types.String                `tfsdk:"region"`
	Service                               types.String                `tfsdk:"service"`
	TotalComments                         types.Int64                 `tfsdk:"total_comments"`
	TotalCount                            types.Int64                 `tfsdk:"total_count"`
	UsergroupNamedNetworkAssignments      types.Int64                 `tfsdk:"usergroup_named_network_assignments"`
}

// Metadata returns the data source type name.
func (r *NamedNetworkDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_named_network"
}

// Schema defines the schema for the data source.
func (r *NamedNetworkDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "NamedNetwork DataSource",

		Attributes: map[string]schema.Attribute{
			"assigned_by_tag_based_policy": schema.BoolAttribute{
				Computed: true,
			},
			"colortokens_managed": schema.BoolAttribute{
				Computed: true,
			},
			"domain": schema.StringAttribute{
				Computed: true,
			},
			"id": schema.StringAttribute{
				Computed:    true,
				Optional:    true,
				Description: "ID of the named network. Either id or named_network_name must be provided.",
			},
			"ip_ranges": schema.ListNestedAttribute{
				Computed: true,
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"id": schema.StringAttribute{
							Computed: true,
						},
						"ip_count": schema.Int64Attribute{
							Computed: true,
						},
						"ip_range": schema.StringAttribute{
							Computed: true,
						},
					},
				},
			},
			"named_network_assignments": schema.Int64Attribute{
				Computed: true,
			},
			"named_network_description": schema.StringAttribute{
				Computed: true,
			},
			"named_network_name": schema.StringAttribute{
				Computed:    true,
				Optional:    true,
				Description: "Name of the named network to look up. Either id or named_network_name must be provided.",
			},
			"namednetwork_tag_based_policy_assignments": schema.Int64Attribute{
				Computed: true,
			},
			"program_as_internet": schema.BoolAttribute{
				Computed: true,
			},
			"program_as_intranet": schema.BoolAttribute{
				Computed: true,
			},
			"region": schema.StringAttribute{
				Computed: true,
			},
			"service": schema.StringAttribute{
				Computed: true,
			},
			"total_comments": schema.Int64Attribute{
				Computed: true,
			},
			"total_count": schema.Int64Attribute{
				Computed: true,
			},
			"usergroup_named_network_assignments": schema.Int64Attribute{
				Computed: true,
			},
		},
	}
}

func (r *NamedNetworkDataSource) Configure(ctx context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	// Prevent panic if the provider has not been configured.
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*sdk.Xshield)

	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected DataSource Configure Type",
			fmt.Sprintf("Expected *sdk.Xshield, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)

		return
	}

	r.client = client
}

func (r *NamedNetworkDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data *NamedNetworkDataSourceModel
	var item types.Object

	resp.Diagnostics.Append(req.Config.Get(ctx, &item)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(item.As(ctx, &data, basetypes.ObjectAsOptions{
		UnhandledNullAsEmpty:    true,
		UnhandledUnknownAsEmpty: true,
	})...)

	if resp.Diagnostics.HasError() {
		return
	}

	// Check if we have an ID or a name
	var res *operations.GetNamedNetworkResponse
	var err error

	if !data.ID.IsNull() && data.ID.ValueString() != "" {
		// If we have an ID, use GetNamedNetwork
		namedNetworkID := data.ID.ValueString()
		request := operations.GetNamedNetworkRequest{
			NamedNetworkID: namedNetworkID,
		}
		res, err = r.client.Namednetworks.GetNamedNetwork(ctx, request)
	} else if !data.NamedNetworkName.IsNull() && data.NamedNetworkName.ValueString() != "" {
		// If we have a name, use ListNamedNetworks with a search criteria
		namedNetworkName := data.NamedNetworkName.ValueString()
		searchCriteria := fmt.Sprintf("namedNetworkName = '%s'", namedNetworkName)
		listReq := operations.ListNamedNetworksRequest{
			SearchInput: shared.SearchInput{
				Criteria: searchCriteria,
			},
		}

		// Call the API
		networks, err := r.client.Namednetworks.ListNamedNetworks(ctx, listReq)
		if err != nil {
			resp.Diagnostics.AddError(
				"Error retrieving named networks",
				fmt.Sprintf("Could not list named networks to find by name: %s", err),
			)
			return
		}

		// Process the response
		if networks.NamedNetworks != nil && len(networks.NamedNetworks.Items) > 0 {
			// Find the named network with the matching name
			var foundID string
			for _, network := range networks.NamedNetworks.Items {
				if network.NamedNetworkName != nil && *network.NamedNetworkName == namedNetworkName {
					if network.ID != nil {
						foundID = *network.ID
						break
					}
				}
			}

			if foundID != "" {
				// Now use GetNamedNetwork to get the full details
				request := operations.GetNamedNetworkRequest{
					NamedNetworkID: foundID,
				}
				res, err = r.client.Namednetworks.GetNamedNetwork(ctx, request)
			} else {
				resp.Diagnostics.AddError(
					"Named network not found",
					fmt.Sprintf("No named network found with name: %s", namedNetworkName),
				)
				return
			}
		} else {
			resp.Diagnostics.AddError(
				"Named network not found",
				fmt.Sprintf("No named networks found matching the criteria: %s", searchCriteria),
			)
			return
		}
	} else {
		// If we don't have either ID or name, return an error
		resp.Diagnostics.AddError(
			"Missing required attribute",
			"Either id or named_network_name must be provided",
		)
		return
	}
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", err.Error())
		if res != nil && res.RawResponse != nil {
			resp.Diagnostics.AddError("unexpected http request/response", debugResponse(res.RawResponse))
		}
		return
	}
	if res == nil {
		resp.Diagnostics.AddError("unexpected response from API", fmt.Sprintf("%v", res))
		return
	}
	if res.StatusCode == 404 {
		resp.State.RemoveResource(ctx)
		return
	}
	if res.StatusCode != 200 {
		resp.Diagnostics.AddError(fmt.Sprintf("unexpected response from API. Got an unexpected response code %v", res.StatusCode), debugResponse(res.RawResponse))
		return
	}
	if !(res.NamednetworkNamedNetwork != nil) {
		resp.Diagnostics.AddError("unexpected response from API. Got an unexpected response body", debugResponse(res.RawResponse))
		return
	}
	data.RefreshFromSharedNamednetworkNamedNetwork(res.NamednetworkNamedNetwork)

	// Save updated data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
