// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	"fmt"

	tfTypes "github.com/colortokens/terraform-provider-xshield/internal/provider/types"
	"github.com/colortokens/terraform-provider-xshield/internal/sdk"
	"github.com/colortokens/terraform-provider-xshield/internal/sdk/models/operations"
	"github.com/colortokens/terraform-provider-xshield/internal/sdk/models/shared"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ datasource.DataSource = &SegmentDataSource{}
var _ datasource.DataSourceWithConfigure = &SegmentDataSource{}

func NewSegmentDataSource() datasource.DataSource {
	return &SegmentDataSource{}
}

// SegmentDataSource is the data source implementation.
type SegmentDataSource struct {
	client *sdk.Xshield
}

// SegmentDataSourceModel describes the data model.
type SegmentDataSourceModel struct {
	BaselineBreachImpactScore            types.Int64                             `tfsdk:"baseline_breach_impact_score"`
	BaselineMatchingAssets               types.Int64                             `tfsdk:"baseline_matching_assets"`
	Criteria                             types.String                            `tfsdk:"criteria"`
	CriteriaAsParams                     types.String                            `tfsdk:"criteria_as_params"`
	Description                          types.String                            `tfsdk:"description"`
	ID                                   types.String                            `tfsdk:"id"`
	InboundAutoSyncDeploymentMode        types.String                            `tfsdk:"inbound_auto_sync_deployment_mode"`
	InboundAutoSyncIntervalMinutes       types.Int64                             `tfsdk:"inbound_auto_sync_interval_minutes"`
	InboundAutoSyncIncludeViolations     types.Bool                              `tfsdk:"inbound_auto_sync_include_violations"`
	InboundAutoSyncViolationThreshold    types.Int64                             `tfsdk:"inbound_auto_sync_violation_threshold"`
	OutboundAutoSyncDeploymentMode       types.String                            `tfsdk:"outbound_auto_sync_deployment_mode"`
	OutboundAutoSyncIntervalMinutes      types.Int64                             `tfsdk:"outbound_auto_sync_interval_minutes"`
	OutboundAutoSyncIncludeViolations    types.Bool                              `tfsdk:"outbound_auto_sync_include_violations"`
	OutboundAutoSyncViolationThreshold   types.Int64                             `tfsdk:"outbound_auto_sync_violation_threshold"`
	LowestInboundPolicyStatus            types.String                            `tfsdk:"lowest_inbound_policy_status"`
	LowestOutboundPolicyStatus           types.String                            `tfsdk:"lowest_outbound_policy_status"`
	LowestProgressiveInboundPolicyStatus types.String                            `tfsdk:"lowest_progressive_inbound_policy_status"`
	MatchingAssets                       types.Int64                             `tfsdk:"matching_assets"`
	Milestones                           []tfTypes.TagBasedPolicyMilestone       `tfsdk:"milestones"`
	Namednetworks                        []tfTypes.MetadataNamedNetworkReference `tfsdk:"namednetworks"`
	PolicyAutomationConfigurable         types.Bool                              `tfsdk:"policy_automation_configurable"`
	TagBasedPolicyName                   types.String                            `tfsdk:"tag_based_policy_name"`
	TargetBreachImpactScore              types.Int64                             `tfsdk:"target_breach_impact_score"`
	Templates                            []tfTypes.TemplateReference             `tfsdk:"templates"`
	Timeline                             types.Int64                             `tfsdk:"timeline"`
}

// Metadata returns the data source type name.
func (r *SegmentDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_segment"
}

// Schema defines the schema for the data source.
func (r *SegmentDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Segment DataSource",

		Attributes: map[string]schema.Attribute{
			"baseline_breach_impact_score": schema.Int64Attribute{
				Computed: true,
			},
			"baseline_matching_assets": schema.Int64Attribute{
				Computed: true,
			},
			"criteria": schema.StringAttribute{
				Computed: true,
			},
			"criteria_as_params": schema.StringAttribute{
				Computed: true,
			},
			"description": schema.StringAttribute{
				Computed: true,
			},
			"id": schema.StringAttribute{
				Computed:    true,
				Optional:    true,
				Description: "ID of the segment. Either id or tag_based_policy_name must be provided.",
			},
			"inbound_auto_sync_deployment_mode": schema.StringAttribute{
				Computed: true,
			},
			"inbound_auto_sync_interval_minutes": schema.Int64Attribute{
				Computed: true,
			},
			"inbound_auto_sync_include_violations": schema.BoolAttribute{
				Computed: true,
			},
			"inbound_auto_sync_violation_threshold": schema.Int64Attribute{
				Computed: true,
			},
			"outbound_auto_sync_deployment_mode": schema.StringAttribute{
				Computed: true,
			},
			"outbound_auto_sync_interval_minutes": schema.Int64Attribute{
				Computed: true,
			},
			"outbound_auto_sync_include_violations": schema.BoolAttribute{
				Computed: true,
			},
			"outbound_auto_sync_violation_threshold": schema.Int64Attribute{
				Computed: true,
			},
			"lowest_inbound_policy_status": schema.StringAttribute{
				Computed: true,
			},
			"lowest_outbound_policy_status": schema.StringAttribute{
				Computed: true,
			},
			"lowest_progressive_inbound_policy_status": schema.StringAttribute{
				Computed: true,
			},
			"matching_assets": schema.Int64Attribute{
				Computed: true,
			},
			"milestones": schema.ListNestedAttribute{
				Computed: true,
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"completion_percentage": schema.NumberAttribute{
							Computed: true,
						},
						"milestone_id": schema.Int64Attribute{
							Computed: true,
						},
						"name": schema.StringAttribute{
							Computed: true,
						},
					},
				},
			},
			"namednetworks": schema.ListNestedAttribute{
				Computed: true,
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"named_network_id": schema.StringAttribute{
							Computed: true,
						},
						"named_network_name": schema.StringAttribute{
							Computed: true,
						},
					},
				},
			},
			"policy_automation_configurable": schema.BoolAttribute{
				Computed: true,
			},
			"tag_based_policy_name": schema.StringAttribute{
				Computed:    true,
				Optional:    true,
				Description: "Name of the segment to look up. Either id or tag_based_policy_name must be provided.",
			},
			"target_breach_impact_score": schema.Int64Attribute{
				Computed: true,
			},
			"templates": schema.ListNestedAttribute{
				Computed: true,
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"template_id": schema.StringAttribute{
							Computed: true,
						},
						"template_name": schema.StringAttribute{
							Computed: true,
							Validators: []validator.String{
								stringvalidator.LengthAtMost(256),
							},
							Description: `Template name. Maximum length is 256 characters.`,
						},
					},
				},
			},
			"timeline": schema.Int64Attribute{
				Computed: true,
			},
		},
	}
}

func (r *SegmentDataSource) Configure(ctx context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	// Prevent panic if the provider has not been configured.
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*sdk.Xshield)

	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected DataSource Configure Type",
			fmt.Sprintf("Expected *sdk.Xshield, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)

		return
	}

	r.client = client
}

func (r *SegmentDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data *SegmentDataSourceModel
	var item types.Object

	resp.Diagnostics.Append(req.Config.Get(ctx, &item)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(item.As(ctx, &data, basetypes.ObjectAsOptions{
		UnhandledNullAsEmpty:    true,
		UnhandledUnknownAsEmpty: true,
	})...)

	if resp.Diagnostics.HasError() {
		return
	}

	// Check if we have an ID or a name
	var res *operations.GetTagBasedPolicyResponse
	var err error

	if !data.ID.IsNull() && data.ID.ValueString() != "" {
		// If we have an ID, use GetTagBasedPolicy
		tagbasedpolicyID := data.ID.ValueString()
		request := operations.GetTagBasedPolicyRequest{
			TagbasedpolicyID: tagbasedpolicyID,
		}
		res, err = r.client.Tagbasedpolicies.GetTagBasedPolicy(ctx, request)
	} else if !data.TagBasedPolicyName.IsNull() && data.TagBasedPolicyName.ValueString() != "" {
		// If we have a name, use ListTagBasedPolicies with a search criteria
		policyName := data.TagBasedPolicyName.ValueString()
		searchCriteria := fmt.Sprintf("tagBasedPolicyName = '%s'", policyName)
		listReq := operations.ListTagBasedPoliciesRequest{
			SearchInput: shared.SearchInput{
				Criteria: searchCriteria,
			},
		}

		// Call the API
		policies, err := r.client.Tagbasedpolicies.ListTagBasedPolicies(ctx, listReq)
		if err != nil {
			resp.Diagnostics.AddError(
				"Error retrieving segments",
				fmt.Sprintf("Could not list segments to find by name: %s", err),
			)
			return
		}

		// Process the response
		if policies.TagBasedPolicies != nil && len(policies.TagBasedPolicies.Items) > 0 {
			// Find the segment with the matching name
			var foundID string
			for _, policy := range policies.TagBasedPolicies.Items {
				if policy.TagBasedPolicyName != nil && *policy.TagBasedPolicyName == policyName {
					if policy.TagBasedPolicyID != nil {
						foundID = *policy.TagBasedPolicyID
						break
					}
				}
			}

			if foundID != "" {
				// Now use GetTagBasedPolicy to get the full details
				request := operations.GetTagBasedPolicyRequest{
					TagbasedpolicyID: foundID,
				}
				res, err = r.client.Tagbasedpolicies.GetTagBasedPolicy(ctx, request)
			} else {
				resp.Diagnostics.AddError(
					"Segment not found",
					fmt.Sprintf("No segment found with name: %s", policyName),
				)
				return
			}
		} else {
			resp.Diagnostics.AddError(
				"Segment not found",
				fmt.Sprintf("No segments found matching the criteria: %s", searchCriteria),
			)
			return
		}
	} else {
		// If we don't have either ID or name, return an error
		resp.Diagnostics.AddError(
			"Missing required attribute",
			"Either id or tag_based_policy_name must be provided",
		)
		return
	}
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", err.Error())
		if res != nil && res.RawResponse != nil {
			resp.Diagnostics.AddError("unexpected http request/response", debugResponse(res.RawResponse))
		}
		return
	}
	if res == nil {
		resp.Diagnostics.AddError("unexpected response from API", fmt.Sprintf("%v", res))
		return
	}
	if res.StatusCode == 404 {
		resp.State.RemoveResource(ctx)
		return
	}
	if res.StatusCode != 200 {
		resp.Diagnostics.AddError(fmt.Sprintf("unexpected response from API. Got an unexpected response code %v", res.StatusCode), debugResponse(res.RawResponse))
		return
	}
	if !(res.TagBasedPolicyResponse != nil) {
		resp.Diagnostics.AddError("unexpected response from API. Got an unexpected response body", debugResponse(res.RawResponse))
		return
	}
	data.RefreshFromSharedTagBasedPolicyResponse(res.TagBasedPolicyResponse)

	// Save updated data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
