// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"time"

	tfTypes "github.com/colortokens/terraform-provider-xshield/internal/provider/types"
	"github.com/colortokens/terraform-provider-xshield/internal/sdk/models/shared"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

func (r *SegmentResourceModel) ToSharedTagBasedPolicy() *shared.TagBasedPolicy {
	id := new(string)
	if !r.ID.IsUnknown() && !r.ID.IsNull() {
		*id = r.ID.ValueString()
	} else {
		id = nil
	}
	description := new(string)
	if !r.Description.IsUnknown() && !r.Description.IsNull() {
		*description = r.Description.ValueString()
	} else {
		description = nil
	}
	tagBasedPolicyName := new(string)
	if !r.TagBasedPolicyName.IsUnknown() && !r.TagBasedPolicyName.IsNull() {
		*tagBasedPolicyName = r.TagBasedPolicyName.ValueString()
	} else {
		tagBasedPolicyName = nil
	}
	targetBreachImpactScore := new(int64)
	if !r.TargetBreachImpactScore.IsUnknown() && !r.TargetBreachImpactScore.IsNull() {
		*targetBreachImpactScore = r.TargetBreachImpactScore.ValueInt64()
	} else {
		targetBreachImpactScore = nil
	}
	timeline := new(int64)
	if !r.Timeline.IsUnknown() && !r.Timeline.IsNull() {
		*timeline = r.Timeline.ValueInt64()
	} else {
		timeline = nil
	}
	criteria := new(string)
	if !r.Criteria.IsUnknown() && !r.Criteria.IsNull() {
		*criteria = r.Criteria.ValueString()
	} else {
		criteria = nil
	}
	var namednetworks []shared.MetadataNamedNetworkReference = []shared.MetadataNamedNetworkReference{}
	for _, namednetworksItem := range r.Namednetworks {
		namedNetworkID := new(string)
		if !namednetworksItem.NamedNetworkID.IsUnknown() && !namednetworksItem.NamedNetworkID.IsNull() {
			*namedNetworkID = namednetworksItem.NamedNetworkID.ValueString()
		} else {
			namedNetworkID = nil
		}
		namedNetworkName := new(string)
		if !namednetworksItem.NamedNetworkName.IsUnknown() && !namednetworksItem.NamedNetworkName.IsNull() {
			*namedNetworkName = namednetworksItem.NamedNetworkName.ValueString()
		} else {
			namedNetworkName = nil
		}
		namednetworks = append(namednetworks, shared.MetadataNamedNetworkReference{
			NamedNetworkID:   namedNetworkID,
			NamedNetworkName: namedNetworkName,
		})
	}
	var templates []shared.TemplateReference = []shared.TemplateReference{}
	for _, templatesItem := range r.Templates {
		templateID := new(string)
		if !templatesItem.TemplateID.IsUnknown() && !templatesItem.TemplateID.IsNull() {
			*templateID = templatesItem.TemplateID.ValueString()
		} else {
			templateID = nil
		}
		templateName := new(string)
		if !templatesItem.TemplateName.IsUnknown() && !templatesItem.TemplateName.IsNull() {
			*templateName = templatesItem.TemplateName.ValueString()
		} else {
			templateName = nil
		}
		templates = append(templates, shared.TemplateReference{
			TemplateID:   templateID,
			TemplateName: templateName,
		})
	}
	out := shared.TagBasedPolicy{
		ID:                      id,
		Description:             description,
		TagBasedPolicyName:      tagBasedPolicyName,
		TargetBreachImpactScore: targetBreachImpactScore,
		Timeline:                timeline,
		Criteria:                criteria,
		Namednetworks:           namednetworks,
		Templates:               templates,
	}
	return &out
}

func (r *SegmentResourceModel) RefreshFromSharedTagBasedPolicyResponse(resp *shared.TagBasedPolicyResponse) {
	if resp != nil {
		if resp.Criteria != nil {
			r.Criteria = types.StringValue(*resp.Criteria)
		} else {
			r.Criteria = types.StringNull()
		}
		r.Description = types.StringPointerValue(resp.Description)
		r.ID = types.StringPointerValue(resp.ID)
		r.InboundAutoSyncDeploymentMode = types.StringPointerValue(resp.InboundAutoSyncDeploymentMode)
		r.InboundAutoSyncIntervalMinutes = types.Int64PointerValue(resp.InboundAutoSyncIntervalMinutes)
		r.InboundAutoSyncIncludeViolations = types.BoolPointerValue(resp.InboundAutoSyncIncludeViolations)
		r.InboundAutoSyncViolationThreshold = types.Int64PointerValue(resp.InboundAutoSyncViolationThreshold)
		r.OutboundAutoSyncDeploymentMode = types.StringPointerValue(resp.OutboundAutoSyncDeploymentMode)
		r.OutboundAutoSyncIntervalMinutes = types.Int64PointerValue(resp.OutboundAutoSyncIntervalMinutes)
		r.OutboundAutoSyncIncludeViolations = types.BoolPointerValue(resp.OutboundAutoSyncIncludeViolations)
		r.OutboundAutoSyncViolationThreshold = types.Int64PointerValue(resp.OutboundAutoSyncViolationThreshold)
		r.LowestInboundSegmentAssetPolicyStatus = types.StringPointerValue(resp.LowestInboundSegmentAssetPolicyStatus)
		r.LowestOutboundSegmentAssetPolicyStatus = types.StringPointerValue(resp.LowestOutboundSegmentAssetPolicyStatus)
		r.Namednetworks = []tfTypes.MetadataNamedNetworkReference{}
		if len(r.Namednetworks) > len(resp.Namednetworks) {
			r.Namednetworks = r.Namednetworks[:len(resp.Namednetworks)]
		}
		for namednetworksCount, namednetworksItem := range resp.Namednetworks {
			var namednetworks1 tfTypes.MetadataNamedNetworkReference
			namednetworks1.NamedNetworkID = types.StringPointerValue(namednetworksItem.NamedNetworkID)
			namednetworks1.NamedNetworkName = types.StringPointerValue(namednetworksItem.NamedNetworkName)
			if namednetworksCount+1 > len(r.Namednetworks) {
				r.Namednetworks = append(r.Namednetworks, namednetworks1)
			} else {
				r.Namednetworks[namednetworksCount].NamedNetworkID = namednetworks1.NamedNetworkID
				r.Namednetworks[namednetworksCount].NamedNetworkName = namednetworks1.NamedNetworkName
			}
		}
		r.TagBasedPolicyName = types.StringPointerValue(resp.TagBasedPolicyName)
		r.TargetBreachImpactScore = types.Int64PointerValue(resp.TargetBreachImpactScore)
		r.Templates = []tfTypes.TemplateReference{}
		if len(r.Templates) > len(resp.Templates) {
			r.Templates = r.Templates[:len(resp.Templates)]
		}
		for templatesCount, templatesItem := range resp.Templates {
			var templates1 tfTypes.TemplateReference
			templates1.TemplateID = types.StringPointerValue(templatesItem.TemplateID)
			templates1.TemplateName = types.StringPointerValue(templatesItem.TemplateName)
			if templatesCount+1 > len(r.Templates) {
				r.Templates = append(r.Templates, templates1)
			} else {
				r.Templates[templatesCount].TemplateID = templates1.TemplateID
				r.Templates[templatesCount].TemplateName = templates1.TemplateName
			}
		}
		r.Timeline = types.Int64PointerValue(resp.Timeline)

		// Handle time fields
		if resp.CreatedAt != nil && !resp.CreatedAt.Time.IsZero() {
			r.CreatedAt = types.StringValue(resp.CreatedAt.Time.Format(time.RFC3339))
		} else {
			r.CreatedAt = types.StringNull()
		}
	}
}
