// Code originally generated by Speakeasy (https://www.speakeasyapi.dev).

package provider

import (
	"context"
	"fmt"

	"github.com/colortokens/terraform-provider-xshield/internal/sdk"
	"github.com/colortokens/terraform-provider-xshield/internal/sdk/models/operations"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &TagRuleResource{}
var _ resource.ResourceWithImportState = &TagRuleResource{}

func NewTagRuleResource() resource.Resource {
	return &TagRuleResource{}
}

// TagRuleResource defines the resource implementation.
type TagRuleResource struct {
	client *sdk.Xshield
}

// TagRuleResourceModel describes the resource data model.
type TagRuleResourceModel struct {
	ID              types.String            `tfsdk:"id"`
	OnMatch         map[string]types.String `tfsdk:"on_match"`
	RuleCriteria    types.String            `tfsdk:"rule_criteria"`
	RuleDescription types.String            `tfsdk:"rule_description"`
	RuleEnabled     types.Bool              `tfsdk:"rule_enabled"`
	RuleName        types.String            `tfsdk:"rule_name"`
}

func (r *TagRuleResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_tag_rule"
}

func (r *TagRuleResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "A tag rule: a criteria that, when it matches an asset, applies the tags " +
			"in `on_match` to it. Tag rules are how assets acquire the tags that segment criteria " +
			"then select on.\n\n" +
			"How many assets a rule currently matches is a live property of the tenant, recomputed as " +
			"assets are created, changed and deleted, so it is not part of this resource. Read it from " +
			"the `xshield_tag_rule` data source for one rule or `xshield_tag_rules` for all of them. " +
			"To size a criteria before writing a rule, use `xshield_criteria`, which also warns when " +
			"the criteria selects nothing and returns sample asset names.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Description: `The unique identifier of this tag rule resource.`,
				Computed:    true,
			},
			"on_match": schema.MapAttribute{
				Description: `Key-value pairs to apply as tags when the rule criteria matches an asset. Keys represent tag names and values represent tag values.`,
				Computed:    true,
				Optional:    true,
				ElementType: types.StringType,
			},
			"rule_criteria": schema.StringAttribute{
				Description: `Criteria expression that defines when this tag rule should be applied. Uses the same expression language as segments.`,
				Required:    true,
			},
			"rule_description": schema.StringAttribute{
				Description: `Description of the tag rule explaining its purpose and function.`,
				Computed:    true,
				Optional:    true,
			},
			"rule_enabled": schema.BoolAttribute{
				Description: `Whether the tag rule is currently active and being evaluated against assets. Default is true.`,
				Computed:    true,
				Optional:    true,
			},
			"rule_name": schema.StringAttribute{
				Description: `Name of the tag rule for identification and display purposes.`,
				Computed:    true,
				Optional:    true,
			},
		},
	}
}

func (r *TagRuleResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	// Prevent panic if the provider has not been configured.
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*sdk.Xshield)

	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *sdk.Xshield, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)

		return
	}

	r.client = client
}

func (r *TagRuleResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data *TagRuleResourceModel
	var plan types.Object

	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(plan.As(ctx, &data, basetypes.ObjectAsOptions{
		UnhandledNullAsEmpty:    true,
		UnhandledUnknownAsEmpty: true,
	})...)

	if resp.Diagnostics.HasError() {
		return
	}

	request := *data.ToSharedTagRuleInput()
	res, err := r.client.Tagrules.CreateTagRule(ctx, request)
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", err.Error())
		if res != nil && res.RawResponse != nil {
			resp.Diagnostics.AddError("unexpected http request/response", debugResponse(res.RawResponse))
		}
		return
	}
	if res == nil {
		resp.Diagnostics.AddError("unexpected response from API", fmt.Sprintf("%v", res))
		return
	}
	if res.StatusCode != 202 {
		resp.Diagnostics.AddError(fmt.Sprintf("unexpected response from API. Got an unexpected response code %v", res.StatusCode), debugResponse(res.RawResponse))
		return
	}
	if !(res.TagRule != nil) {
		resp.Diagnostics.AddError("unexpected response from API. Got an unexpected response body", debugResponse(res.RawResponse))
		return
	}
	data.RefreshFromSharedTagRule(res.TagRule)
	refreshPlan(ctx, plan, &data, resp.Diagnostics)

	// Save updated data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *TagRuleResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data *TagRuleResourceModel
	var item types.Object

	resp.Diagnostics.Append(req.State.Get(ctx, &item)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(item.As(ctx, &data, basetypes.ObjectAsOptions{
		UnhandledNullAsEmpty:    true,
		UnhandledUnknownAsEmpty: true,
	})...)

	if resp.Diagnostics.HasError() {
		return
	}

	ruleID := data.ID.ValueString()

	request := operations.GetTagRuleRequest{
		RuleID: ruleID,
	}
	res, err := r.client.Tagrules.GetTagRule(ctx, request)
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", err.Error())
		if res != nil && res.RawResponse != nil {
			resp.Diagnostics.AddError("unexpected http request/response", debugResponse(res.RawResponse))
		}
		return
	}
	if res == nil {
		resp.Diagnostics.AddError("unexpected response from API", fmt.Sprintf("%v", res))
		return
	}
	if res.StatusCode == 404 {
		resp.State.RemoveResource(ctx)
		return
	}
	if res.StatusCode != 200 {
		resp.Diagnostics.AddError(fmt.Sprintf("unexpected response from API. Got an unexpected response code %v", res.StatusCode), debugResponse(res.RawResponse))
		return
	}
	if !(res.TagRule != nil) {
		resp.Diagnostics.AddError("unexpected response from API. Got an unexpected response body", debugResponse(res.RawResponse))
		return
	}
	data.RefreshFromSharedTagRule(res.TagRule)

	// Save updated data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *TagRuleResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var data *TagRuleResourceModel
	var plan types.Object

	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	merge(ctx, req, resp, &data)
	if resp.Diagnostics.HasError() {
		return
	}

	ruleID := data.ID.ValueString()

	tagRule := *data.ToSharedTagRule()
	request := operations.UpdateTagRuleRequest{
		RuleID:  ruleID,
		TagRule: tagRule,
	}
	res, err := r.client.Tagrules.UpdateTagRule(ctx, request)
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", err.Error())
		if res != nil && res.RawResponse != nil {
			resp.Diagnostics.AddError("unexpected http request/response", debugResponse(res.RawResponse))
		}
		return
	}
	if res == nil {
		resp.Diagnostics.AddError("unexpected response from API", fmt.Sprintf("%v", res))
		return
	}
	if res.StatusCode != 200 && res.StatusCode != 202 {
		resp.Diagnostics.AddError(fmt.Sprintf("unexpected response from API. Got an unexpected response code %v", res.StatusCode), debugResponse(res.RawResponse))
		return
	}
	if !(res.TagRule != nil) {
		resp.Diagnostics.AddError("unexpected response from API. Got an unexpected response body", debugResponse(res.RawResponse))
		return
	}
	data.RefreshFromSharedTagRule(res.TagRule)
	refreshPlan(ctx, plan, &data, resp.Diagnostics)

	// Save updated data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *TagRuleResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var data *TagRuleResourceModel
	var item types.Object

	resp.Diagnostics.Append(req.State.Get(ctx, &item)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(item.As(ctx, &data, basetypes.ObjectAsOptions{
		UnhandledNullAsEmpty:    true,
		UnhandledUnknownAsEmpty: true,
	})...)

	if resp.Diagnostics.HasError() {
		return
	}

	ruleID := data.ID.ValueString()

	request := operations.DeleteTagRuleRequest{
		RuleID: ruleID,
	}
	res, err := r.client.Tagrules.DeleteTagRule(ctx, request)
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", err.Error())
		if res != nil && res.RawResponse != nil {
			resp.Diagnostics.AddError("unexpected http request/response", debugResponse(res.RawResponse))
		}
		return
	}
	if res == nil {
		resp.Diagnostics.AddError("unexpected response from API", fmt.Sprintf("%v", res))
		return
	}
	if res.StatusCode != 200 {
		resp.Diagnostics.AddError(fmt.Sprintf("unexpected response from API. Got an unexpected response code %v", res.StatusCode), debugResponse(res.RawResponse))
		return
	}

}

func (r *TagRuleResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	id := req.ID
	if !isXshieldUUID(id) {
		found, err := findTagRuleIDByName(ctx, r.client, id)
		if err != nil {
			resp.Diagnostics.AddError("Cannot import tag rule by name", err.Error())
			return
		}
		id = found
	}
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), id)...)
}
