// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	"fmt"

	"github.com/colortokens/terraform-provider-xshield/internal/sdk"
	"github.com/colortokens/terraform-provider-xshield/internal/sdk/models/operations"
	"github.com/colortokens/terraform-provider-xshield/internal/sdk/models/shared"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ datasource.DataSource = &TagRuleDataSource{}
var _ datasource.DataSourceWithConfigure = &TagRuleDataSource{}

func NewTagRuleDataSource() datasource.DataSource {
	return &TagRuleDataSource{}
}

// TagRuleDataSource is the data source implementation.
type TagRuleDataSource struct {
	client *sdk.Xshield
}

// TagRuleDataSourceModel describes the data model.
type TagRuleDataSourceModel struct {
	ID              types.String            `tfsdk:"id"`
	MatchingAssets  types.Int64             `tfsdk:"matching_assets"`
	OnMatch         map[string]types.String `tfsdk:"on_match"`
	RuleCriteria    types.String            `tfsdk:"rule_criteria"`
	RuleDescription types.String            `tfsdk:"rule_description"`
	RuleEnabled     types.Bool              `tfsdk:"rule_enabled"`
	RuleName        types.String            `tfsdk:"rule_name"`
}

// Metadata returns the data source type name.
func (r *TagRuleDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_tag_rule"
}

// Schema defines the schema for the data source.
func (r *TagRuleDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "TagRule DataSource",

		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:    true,
				Optional:    true,
				Description: "ID of the tag rule. Either id or rule_name must be provided.",
			},
			"matching_assets": schema.Int64Attribute{
				Computed: true,
			},
			"on_match": schema.MapAttribute{
				Computed:    true,
				ElementType: types.StringType,
			},
			"rule_criteria": schema.StringAttribute{
				Computed: true,
			},
			"rule_description": schema.StringAttribute{
				Computed: true,
			},
			"rule_enabled": schema.BoolAttribute{
				Computed: true,
			},
			"rule_name": schema.StringAttribute{
				Computed:    true,
				Optional:    true,
				Description: "Name of the tag rule to look up. Either id or rule_name must be provided.",
			},
		},
	}
}

func (r *TagRuleDataSource) Configure(ctx context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	// Prevent panic if the provider has not been configured.
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*sdk.Xshield)

	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected DataSource Configure Type",
			fmt.Sprintf("Expected *sdk.Xshield, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)

		return
	}

	r.client = client
}

func (r *TagRuleDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data *TagRuleDataSourceModel
	var item types.Object

	resp.Diagnostics.Append(req.Config.Get(ctx, &item)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(item.As(ctx, &data, basetypes.ObjectAsOptions{
		UnhandledNullAsEmpty:    true,
		UnhandledUnknownAsEmpty: true,
	})...)

	if resp.Diagnostics.HasError() {
		return
	}

	// Check if we have an ID or a name
	var res *operations.GetTagRuleResponse
	var err error

	if !data.ID.IsNull() && data.ID.ValueString() != "" {
		// If we have an ID, use GetTagRule
		ruleID := data.ID.ValueString()
		request := operations.GetTagRuleRequest{
			RuleID: ruleID,
		}
		res, err = r.client.Tagrules.GetTagRule(ctx, request)
	} else if !data.RuleName.IsNull() && data.RuleName.ValueString() != "" {
		// If we have a name, use ListTagRules with a search criteria
		ruleName := data.RuleName.ValueString()
		searchCriteria := fmt.Sprintf("ruleName = '%s'", ruleName)
		listReq := operations.ListTagRulesRequest{
			SearchInput: shared.SearchInput{
				Criteria: searchCriteria,
			},
		}

		// Call the API
		rules, err := r.client.Tagrules.ListTagRules(ctx, listReq)
		if err != nil {
			resp.Diagnostics.AddError(
				"Error retrieving tag rules",
				fmt.Sprintf("Could not list tag rules to find by name: %s", err),
			)
			return
		}

		// Process the response
		if rules.TagRules != nil && len(rules.TagRules.Items) > 0 {
			// Find the tag rule with the matching name
			var foundID string
			for _, rule := range rules.TagRules.Items {
				if rule.RuleName != nil && *rule.RuleName == ruleName {
					if rule.ID != nil {
						foundID = *rule.ID
						break
					}
				}
			}

			if foundID != "" {
				// Now use GetTagRule to get the full details
				request := operations.GetTagRuleRequest{
					RuleID: foundID,
				}
				res, err = r.client.Tagrules.GetTagRule(ctx, request)
			} else {
				resp.Diagnostics.AddError(
					"Tag rule not found",
					fmt.Sprintf("No tag rule found with name: %s", ruleName),
				)
				return
			}
		} else {
			resp.Diagnostics.AddError(
				"Tag rule not found",
				fmt.Sprintf("No tag rules found matching the criteria: %s", searchCriteria),
			)
			return
		}
	} else {
		// If we don't have either ID or name, return an error
		resp.Diagnostics.AddError(
			"Missing required attribute",
			"Either id or rule_name must be provided",
		)
		return
	}
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", err.Error())
		if res != nil && res.RawResponse != nil {
			resp.Diagnostics.AddError("unexpected http request/response", debugResponse(res.RawResponse))
		}
		return
	}
	if res == nil {
		resp.Diagnostics.AddError("unexpected response from API", fmt.Sprintf("%v", res))
		return
	}
	if res.StatusCode == 404 {
		resp.State.RemoveResource(ctx)
		return
	}
	if res.StatusCode != 200 {
		resp.Diagnostics.AddError(fmt.Sprintf("unexpected response from API. Got an unexpected response code %v", res.StatusCode), debugResponse(res.RawResponse))
		return
	}
	if !(res.TagRule != nil) {
		resp.Diagnostics.AddError("unexpected response from API. Got an unexpected response body", debugResponse(res.RawResponse))
		return
	}
	data.RefreshFromSharedTagRule(res.TagRule)

	// Save updated data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
