// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	"fmt"

	tfTypes "github.com/colortokens/terraform-provider-xshield/internal/provider/types"
	"github.com/colortokens/terraform-provider-xshield/internal/sdk"
	"github.com/colortokens/terraform-provider-xshield/internal/sdk/models/operations"
	"github.com/colortokens/terraform-provider-xshield/internal/sdk/models/shared"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ datasource.DataSource = &TemplateDataSource{}
var _ datasource.DataSourceWithConfigure = &TemplateDataSource{}

func NewTemplateDataSource() datasource.DataSource {
	return &TemplateDataSource{}
}

// TemplateDataSource is the data source implementation.
type TemplateDataSource struct {
	client *sdk.Xshield
}

// TemplateDataSourceModel describes the data model.
type TemplateDataSourceModel struct {
	AccessPolicyTemplate types.Bool             `tfsdk:"access_policy_template"`
	ColortokensManaged   types.Bool             `tfsdk:"colortokens_managed"`
	ID                   types.String           `tfsdk:"id"`
	TemplateCategory     types.String           `tfsdk:"template_category"`
	TemplateDescription  types.String           `tfsdk:"template_description"`
	TemplateName         types.String           `tfsdk:"template_name"`
	TemplatePaths        []tfTypes.MetadataPath `tfsdk:"template_paths"`
	TemplatePorts        []tfTypes.MetadataPort `tfsdk:"template_ports"`
	TemplateType         types.String           `tfsdk:"template_type"`
}

// Metadata returns the data source type name.
func (r *TemplateDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_template"
}

// Schema defines the schema for the data source.
func (r *TemplateDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Template DataSource",

		Attributes: map[string]schema.Attribute{
			"access_policy_template": schema.BoolAttribute{
				Computed: true,
			},
			"colortokens_managed": schema.BoolAttribute{
				Computed: true,
			},
			"id": schema.StringAttribute{
				Computed:    true,
				Optional:    true,
				Description: "ID of the template. Either id or template_name must be provided.",
			},
			"template_category": schema.StringAttribute{
				Computed: true,
			},
			"template_description": schema.StringAttribute{
				Computed: true,
			},
			"template_name": schema.StringAttribute{
				Computed:    true,
				Optional:    true,
				Description: "Name of the template to look up. Either id or template_name must be provided.",
			},
			"template_paths": schema.ListNestedAttribute{
				Computed: true,
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"destination_asset_id": schema.StringAttribute{
							Computed: true,
						},
						"destination_named_network": schema.SingleNestedAttribute{
							Computed: true,
							Attributes: map[string]schema.Attribute{
								"named_network_id": schema.StringAttribute{
									Computed: true,
								},
								"named_network_name": schema.StringAttribute{
									Computed: true,
								},
							},
						},
						"destination_tag_based_policy": schema.SingleNestedAttribute{
							Computed: true,
							Attributes: map[string]schema.Attribute{
								"criteria": schema.StringAttribute{
									Computed: true,
								},
								"tag_based_policy_id": schema.StringAttribute{
									Computed: true,
								},
								"tag_based_policy_name": schema.StringAttribute{
									Computed: true,
								},
							},
						},
						"direction": schema.StringAttribute{
							Computed: true,
						},
						"domain": schema.StringAttribute{
							Computed: true,
						},
						"dst_ip": schema.StringAttribute{
							Computed: true,
						},
						"dst_process": schema.StringAttribute{
							Computed: true,
						},
						"id": schema.StringAttribute{
							Computed: true,
						},
						"method": schema.StringAttribute{
							Computed: true,
						},
						"port": schema.StringAttribute{
							Computed: true,
						},
						"port_name": schema.StringAttribute{
							Computed: true,
						},
						"protocol": schema.StringAttribute{
							Computed: true,
						},
						"source_asset_id": schema.StringAttribute{
							Computed: true,
						},
						"source_named_network": schema.SingleNestedAttribute{
							Computed: true,
							Attributes: map[string]schema.Attribute{
								"named_network_id": schema.StringAttribute{
									Computed: true,
								},
								"named_network_name": schema.StringAttribute{
									Computed: true,
								},
							},
						},
						"source_tag_based_policy": schema.SingleNestedAttribute{
							Computed: true,
							Attributes: map[string]schema.Attribute{
								"criteria": schema.StringAttribute{
									Computed: true,
								},
								"tag_based_policy_id": schema.StringAttribute{
									Computed: true,
								},
								"tag_based_policy_name": schema.StringAttribute{
									Computed: true,
								},
							},
						},
						"src_ip": schema.StringAttribute{
							Computed: true,
						},
						"src_process": schema.StringAttribute{
							Computed: true,
						},
						"uri": schema.StringAttribute{
							Computed: true,
						},
						"rule_hit_metrics": schema.SingleNestedAttribute{
							Computed: true,
							Attributes: map[string]schema.Attribute{
								"last_evaluated": schema.StringAttribute{
									Computed: true,
								},
								"total_hits": schema.StringAttribute{
									Computed: true,
								},
							},
						},
					},
				},
			},
			"template_ports": schema.ListNestedAttribute{
				Computed: true,
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"id": schema.StringAttribute{
							Computed: true,
						},
						"listen_port": schema.StringAttribute{
							Computed: true,
						},
						"listen_port_name": schema.StringAttribute{
							Computed: true,
						},
						"listen_port_protocol": schema.StringAttribute{
							Computed: true,
						},
						"listen_port_reviewed": schema.StringAttribute{
							Computed: true,
						},
						"listen_process_names": schema.ListAttribute{
							Computed:    true,
							ElementType: types.StringType,
						},
					},
				},
			},
			"template_type": schema.StringAttribute{
				Computed: true,
			},
		},
	}
}

func (r *TemplateDataSource) Configure(ctx context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	// Prevent panic if the provider has not been configured.
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*sdk.Xshield)

	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected DataSource Configure Type",
			fmt.Sprintf("Expected *sdk.Xshield, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)

		return
	}

	r.client = client
}

func (r *TemplateDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data *TemplateDataSourceModel
	var item types.Object

	resp.Diagnostics.Append(req.Config.Get(ctx, &item)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(item.As(ctx, &data, basetypes.ObjectAsOptions{
		UnhandledNullAsEmpty:    true,
		UnhandledUnknownAsEmpty: true,
	})...)

	if resp.Diagnostics.HasError() {
		return
	}

	// Check if we have an ID or a name
	var res *operations.GetTemplateResponse
	var err error

	if !data.ID.IsNull() && data.ID.ValueString() != "" {
		// If we have an ID, use GetTemplate
		templateid := data.ID.ValueString()
		request := operations.GetTemplateRequest{
			Templateid: templateid,
		}
		res, err = r.client.Templates.GetTemplate(ctx, request)
	} else if !data.TemplateName.IsNull() && data.TemplateName.ValueString() != "" {
		// If we have a name, use ListTemplates with a search criteria
		templateName := data.TemplateName.ValueString()
		searchCriteria := fmt.Sprintf("templateName = '%s'", templateName)
		listReq := operations.ListTemplatesRequest{
			SearchInput: shared.SearchInput{
				Criteria: searchCriteria,
			},
		}

		// Call the API
		templates, err := r.client.Templates.ListTemplates(ctx, listReq)
		if err != nil {
			resp.Diagnostics.AddError(
				"Error retrieving templates",
				fmt.Sprintf("Could not list templates to find by name: %s", err),
			)
			return
		}

		// Process the response
		if templates.Templates != nil && len(templates.Templates.Items) > 0 {
			// Find the template with the matching name
			var foundID string
			for _, template := range templates.Templates.Items {
				if template.TemplateName != nil && *template.TemplateName == templateName {
					if template.TemplateID != nil {
						foundID = *template.TemplateID
						break
					}
				}
			}

			if foundID != "" {
				// Now use GetTemplate to get the full details
				request := operations.GetTemplateRequest{
					Templateid: foundID,
				}
				res, err = r.client.Templates.GetTemplate(ctx, request)
			} else {
				resp.Diagnostics.AddError(
					"Template not found",
					fmt.Sprintf("No template found with name: %s", templateName),
				)
				return
			}
		} else {
			resp.Diagnostics.AddError(
				"Template not found",
				fmt.Sprintf("No templates found matching the criteria: %s", searchCriteria),
			)
			return
		}
	} else {
		// If we don't have either ID or name, return an error
		resp.Diagnostics.AddError(
			"Missing required attribute",
			"Either id or template_name must be provided",
		)
		return
	}
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", err.Error())
		if res != nil && res.RawResponse != nil {
			resp.Diagnostics.AddError("unexpected http request/response", debugResponse(res.RawResponse))
		}
		return
	}
	if res == nil {
		resp.Diagnostics.AddError("unexpected response from API", fmt.Sprintf("%v", res))
		return
	}
	if res.StatusCode == 404 {
		resp.State.RemoveResource(ctx)
		return
	}
	if res.StatusCode != 200 {
		resp.Diagnostics.AddError(fmt.Sprintf("unexpected response from API. Got an unexpected response code %v", res.StatusCode), debugResponse(res.RawResponse))
		return
	}
	if !(res.Template != nil) {
		resp.Diagnostics.AddError("unexpected response from API. Got an unexpected response body", debugResponse(res.RawResponse))
		return
	}
	data.RefreshFromSharedTemplate(res.Template)

	// Save updated data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
