// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

// Program represents a running process in the case of a VM / physical host or may represent a container in context of kubernetes services.
type Program struct {
	Image types.String `tfsdk:"image"`
	Name  types.String `tfsdk:"name"`
	Path  types.String `tfsdk:"path"`
}
