// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type TemplateRuleHitMetrics struct {
	LastEvaluated types.String `tfsdk:"last_evaluated"`
	TotalHits     types.String `tfsdk:"total_hits"`
}
